infix using "C:\NEWSPA_AUG30\HT6A\EXPORT\EXPORTEDFILES\HTSC6AFLSR.dct"

label variable inv_id   "INVENTORY ID"
label variable p_id     "Unit/Provider line number ID"
label variable obs_n    "Client type code"
label variable obs_id   "Client ID"
label variable c000     "Survey phase"
label variable c001     "Region (Country-specific)"
label variable c002     "District (Country-specific)"
label variable c003     "Urban/rural"
label variable c004     "Facility number"
label variable c004p    "Provider line number"
label variable c004ct   "Client type code (alpha)"
label variable c004cn   "Client ID number"
label variable c005     "Sample weight"
label variable c007     "Facility type (Country-specific)"
label variable c008     "Operating Authority (Country-specific)"
label variable c009a    "Interviewer for observation"
label variable c009b    "Interviewer for exit interview"
label variable c009c    "NA - Keyer"
label variable c020a    "Result of observation"
label variable c020b    "Result of exit intervIew"
label variable c021     "Type of client"
label variable c022     "Sex of provider"
label variable c023     "Sex of client/sick child"
label variable c024     "Technical qualification of provider (Country-specific within ranges)"
label variable c032     "Month of observation/interview"
label variable c033     "Year of observation/interview"
label variable c033d    "Day of observation/interview"
label variable c501     "Duration of wait before being seen (in minutes)"
label variable c502a    "Client problem during visit:Time had to wait"
label variable c502b    "Client problem during visit:Ability to discuss problems/concerns"
label variable c502c    "Client problem during visit:Amount of explanation for problem/tx"
label variable c502e    "Client problem during visit:Visual privacy"
label variable c502f    "Client problem during visit:Auditory privacy"
label variable c502g    "Client problem during visit:Availability of medicines at facility"
label variable c502h    "Client problem during visit:Hours of service"
label variable c502i    "Client problem during visit:Days of service"
label variable c502j    "Client problem during visit:Cleanliness of facility"
label variable c502k    "Client problem during visit:Staff treatment of client"
label variable c502l    "Client problem during visit:Cost"
label variable c503     "Part of prepayment plan/insurance that pays part of cost"
label variable c504     "Charged for services today"
label variable c505     "Total amount paid (in gourdes)"
label variable c507     "Facility nearest to home"
label variable c508     "Reason did not go to nearest facility"
label variable c510     "Caretaker relationship to sick child (Sick child exit only)"
label variable c511     "Age of client (caretaker of client)"
label variable c512     "Highest level of education attended"
label variable c514     "Literacy level"
label variable c515     "Country reported highest level of education attended (CS)"
label variable c517a    "Time observation interview began"
label variable c517b    "Time observation interview ended"
label variable c518a    "Time exit interview began"
label variable c518b    "Time exit interview ended"
label variable c520     "Opinion of services given today"
label variable c521     "Would recommend to friend/family member"
label variable c522     "First observation for this provider for this service"
label variable scdepart "CS - Region with West separated for metropolitan and other"
label variable sclocal  "Metropoliltan/other urban/rural"
label variable c202     "First visit (Data from observation)"
label variable c203a    "Main symptoms:Cough or difficult breathing"
label variable c203b    "Main symptoms:Diarrhea"
label variable c203c    "Main symptoms:Fever or body hotness"
label variable c203d    "Main symptoms:Ear problems"
label variable c203y    "Main symptoms:None of the above 4"
label variable c204a    "Other problems General:Unable to drink/breastfeed"
label variable c204b    "Other problems General:Vomiting everything"
label variable c204c    "Other problems General:Had convulsions"
label variable c204d    "Other problems HIV symptomatic:Mother's HIV status"
label variable c204e    "Other problems HIV symptomatic:TB infection in either parent in last 5 years"
label variable c204f    "Other problems HIV symptomatic:Two or more episodes of diarrhea in child each la"
label variable c204y1   "Other problems:None of C204A, B, C"
label variable c204y2   "Other problems HIV symptomatic:None of C204D, E, F"
label variable c205a    "Physical exam: temperature by thermometer"
label variable c205b    "Physical exam: feel for fever or hotness"
label variable c205c    "Physical exam: Count respirations"
label variable c205d    "Physical exam: Auscultate child"
label variable c205e    "Physical exam: Check turgor for dehydration"
label variable c205f    "Physical exam: Check for pallor by looking at palms"
label variable c205g    "Physical exam: Check for pallor by looking at conjunctiva or mouth"
label variable c205h    "Physical exam: Look in ear"
label variable c205i    "Physical exam: Feel behind ear"
label variable c205j    "Physical exam: Undress child to examine"
label variable c205k    "Physical exam: Press feet to check for edema"
label variable c205m    "Physical exam: Weigh the child"
label variable c205n    "Physical exam: Plot weight on growth chart"
label variable c205p    "Physical exam: Look in child's mouth"
label variable c205q    "Physical exam: Check for neck stiffness"
label variable c205r    "Physical exam: Check for enlarged lymph nodes in 2+ sites: neck, axillae, groin"
label variable c205s    "CS Physical exam: Compare child's weight with reference"
label variable c205y    "Physical exam: None of the above physical checks"
label variable cf205a   "Routine action in facility: Take child's temperature"
label variable cf205m   "Routine action in facility: Weigh child"
label variable cf205n   "Routine action in facility: Plot child's weight on graph"
label variable cf205xa  "Routine action in facility: Conduct group health education"
label variable cf205xb  "Routine action in facility: Assess child's vaccination status"
label variable cf205xc  "Routine action in facility: Administer fever-reducing med/ sponge for fever"
label variable cf205xd  "Routine action in facility: Triage children"
label variable cf205xe  "NA - Routine action in facility: CS"
label variable c206a    "Other assessments:Offered breast or drink"
label variable c206b    "Other assessments:Normal feeding when not ill"
label variable c206c    "Other assessments:Normal breastfeeding when not ill"
label variable c206d    "Other assessments:Feeding or breastfeeding during this illness"
label variable c206e    "Other assessments:Discuss weight/growth/growth chart"
label variable c206f    "Other assessments:Review immunization card or ask about vaccination history"
label variable c206g    "Other assessments:Ask if child received vitamin A within past 6 months"
label variable c206i    "Other assessments:Asked if child received de-worming medication in last 6 months"
label variable c206y    "Other assessments:None of the above"
label variable c207a    "Caretaker counseling:Provide general information about feeding/breastfeeding whe"
label variable c207b    "Caretaker counseling:Advise extra fluids during this sickness"
label variable c207c    "Caretaker counseling:Advise continued feeding during sickness"
label variable c207d    "Caretaker counseling:Name the illness for the caretaker"
label variable c207e    "Caretaker counseling:Describe symptoms requiring immediate return for care"
label variable c207f    "Caretaker counseling:Used visual aid to educate the caretaker"
label variable c207y    "Caretaker counseling:No caretaker counseling"
label variable c208b    "Referral:Child referred to other provider"
label variable c208c    "Referral:Child referred to lab for test"
label variable c208d    "Referral:Provider explained referral"
label variable c208e    "Referral:Referral slip given"
label variable c208f    "Referral:Told where to go and whom to see"
label variable c208g    "Referral:Told when to go"
label variable c208h    "Referral:Recommended child be hospitalized urgently"
label variable c208y    "Referral:No referrals"
label variable c209a    "Home meds:Oral medications prescribed or provided for home treatment"
label variable c209b    "Home meds:Oral medication administration explained"
label variable c209c    "Home meds:Caretaker asked to repeat instructions"
label variable c209d    "Home meds:Oral medications - first dose given"
label variable c209y    "Home meds:Oral medications - none prescribed or given"
label variable c211a    "Child's health card: Provider referred to it"
label variable c211b    "Child's health card: Provider wrote on it"
label variable c212     "Follow-up discussed"
label variable c213     "Outcome of consultation"
label variable c220     "Asked provider for diagnosis"
label variable c221a    "Diagnosis Respiratory:Pneumonia/ Broncopneumonia"
label variable c221c    "Diagnosis Respiratory:Bronchial Spasm/asthma"
label variable c221d    "Diagnosis Respiratory:Upper respiratory infection (URI)"
label variable c221e    "Diagnosis Respiratory:Respiratory illness, diagnosis uncertain"
label variable c221f    "Diagnosis Respiratory:Cough, diagnosis uncertain"
label variable c221y    "Diagnosis Respiratory:No respiratory diagnosis"
label variable c222a    "NA - Diagnosis Digestive:Persistent diarrhea"
label variable c222b    "NA - Diagnosis Digestive:Diarrhea"
label variable c222c    "Diagnosis Digestive:Dysentery"
label variable c222d    "Diagnosis Digestive:Amebiasis"
label variable c222e    "Diagnosis Digestive:Other digestive/diarrhea"
label variable c222f    "Diagnosis Digestive:Acute watery diarrhea"
label variable c222y    "Diagnosis Digestive:No digestive diagnosis"
label variable c223a    "Diagnosis:Dehydration * special codes"
label variable c224a    "Diagnosis Malaria:Clinical diagnosis"
label variable c224b    "Diagnosis Malaria:Blood smear"
label variable c224d    "Diagnosis Malaria:RDT"
label variable c224y    "Diagnosis Malaria:No malaria diagnosis"
label variable c225a    "Diagnosis Fever/Measles:Fever of unknown origin"
label variable c225b    "Diagnosis Fever/Measles:Measles with no complications"
label variable c225c    "Diagnosis Fever/Measles:Measles with complications"
label variable c225d    "NA - Diagnosis Fever/Measles:Typhoid fever"
label variable c225e    "NA - Diagnosis Fever/Measles:Urinary track infection"
label variable c225f    "NA - Diagnosis Fever/Measles:Septicemia"
label variable c225g    "NA - Diagnosis Fever/Measles:Meningitis"
label variable c225y    "Diagnosis Fever/Measles:No fever/ measles diagnosis"
label variable c226a    "Diagnosis Ear:Mastoiditis"
label variable c226b    "Diagnosis Ear:Acute ear infections"
label variable c226c    "Diagnosis Ear:Chronic ear infection"
label variable c226d    "Diagnosis Ear:Other ear infection"
label variable c226y    "Diagnosis Ear:No ear diagnosis"
label variable c227a    "NA - Diagnosis Throat:Streptococcal sore throat"
label variable c227b    "NA - Diagnosis Throat:Non-streptococcal sore throat"
label variable c227c    "Diagnosis Throat:Other throat diagnosis"
label variable c227d    "Diagnosis Sore throat (Pharyngitis)"
label variable c227y    "Diagnosis Throat:No throat diagnosis"
label variable c228a    "Diagnosis:Other diagnosis"
label variable c228b    "NA - Diagnosis:Abscess"
label variable c228c    "NA - Diagnosis:Bacterial conjunctivitis"
label variable c228d    "NA - Diagnosis:Skin condition"
label variable c228y    "Diagnosis:No other diagnosis"
label variable c230_36y "No treatment prescribed during consult"
label variable c230a    "Treatment General med:Benzyl penicillin injection"
label variable c230b    "Treatment General med:Other antibiotic injection"
label variable c230c    "Treatment General med:Other injection"
label variable c230e    "Treatment General med:Other antibiotic tablet/syrup"
label variable c230f    "Treatment General med:Paracetamol"
label variable c230g    "Treatment General med:Vitamins"
label variable c230h    "Treatment General med:Cough syrups/other meds for symptomatic tx"
label variable c230i    "Treatment General med:Zinc"
label variable c230j    "Treatment General med:Co-trimoxazole tablets"
label variable c230k    "Treatment General med:Co-trimoxazole syrup"
label variable c230l    "Treatment General med:Amoxicillin capsules"
label variable c230m    "Treatment General med:Amoxicillin syrup"
label variable c230n    "Treatment General med:Fever reducing other than paracetamol"
label variable c230y    "Treatment General med:No general treatment medication"
label variable c232a    "Treatment Respiratory:Nebulilzer or inhaler"
label variable c232b    "Treatment Respiratory:Injectable bronchodilator (adrenaline)"
label variable c232c    "Treatment Respiratory:Oral bronchodilator"
label variable c232d    "Treatment Respiratory:Dry ear by wickIng"
label variable c232y    "Treatment Respiratory:No respiratory treatment"
label variable c233a    "Treatment Malaria injectable:Quinine"
label variable c233c    "Treatment Malaria injectable:Other injectable antimalarial"
label variable c233e    "NA - Treatment Malaria injectable:Artemether/ artesunate"
label variable c233f    "NA - Treatment Malaria suppository:Artemether/ artesunate"
label variable c234a    "Treatment Malaria oral:Fansidar (SP)"
label variable c234b    "NA - Treatment Malaria oral:Artemisinin (incl ACT, COARTEM)"
label variable c234c    "NA - Treatment Malaria oral:Amodiaquine"
label variable c234d    "NA - Treatment Malaria oral:Artemether/ Artesunate"
label variable c234e    "NA - Treatment Malaria oral:Quinine"
label variable c234f    "CS - Treatment Malaria oral: Chloroquine"
label variable c234g    "CS - Treatment Malaria oral: Primaquine"
label variable c234h    "CS - Treatment Malaria oral: Mefloquine"
label variable c234x    "Treatment Malaria oral:Other antimalarial"
label variable c234y    "Treatment Malaria:No antimalarial treatment for C233/C234"
label variable c235a    "Treatment Dehydration:Home ORT"
label variable c235b    "Treatment Dehydration:Initial ORT in facility (4 hours)"
label variable c235c    "Treatment Dehydration:Intravenous fluids"
label variable c235y    "Treatment Dehydration:No dehydration treatment"
label variable c236a    "Treatment Other:Vitamin A"
label variable c236b    "Treatment Other:Feeding solid foods"
label variable c236c    "Treatment Other:Feeding extra liquids"
label variable c236d    "Treatment Other:Feeding breast milk"
label variable c236e    "Treatment Other:Prescribe de-worming medication"
label variable c236x    "Treatment Other:Other"
label variable c236y    "Treatment Other:No other treatment"
label variable c238     "Child given vaccination"
label variable c239     "Reason no vaccination given"
label variable c250     "Century month code of birth of child (imputed)"
label variable c251     "Month of birth of child"
label variable c252     "Year of birth of child"
label variable c253     "Age in months of child"
label variable c254     "Flag for date of birth"
label variable c255a    "Health reason for visit:Cough or difficult breathing"
label variable c255b    "Health reason for visit:Diarrhea"
label variable c255c    "Health reason for visit:Fever/body hotness at home"
label variable c255d    "Health reason for visit:Vomit everything"
label variable c255e    "Health reason for visit:Feeding, drinking problems"
label variable c255f    "Health reason for visit:Convulsions"
label variable c255g    "Health reason for visit:Sleepiness"
label variable c256a    "NA - Other reason for visit:Eye problems"
label variable c256b    "Other reason for visit:Skin sore"
label variable c256c    "Other reason for visit:Injury"
label variable c256d    "Other reason for visit:Ear problem"
label variable c256x    "Other reason for visit:Other"
label variable c256y    "Other reason for visit:No other reason"
label variable c257     "Other visits for same sickness"
label variable c258     "Days ago illness began"
label variable c259     "Provider named the child's illness"
label variable c260     "Caretaker action if child does not get better or gets worse"
label variable c261a    "Danger signs addl tx:Fever"
label variable c261b    "Danger signs addl tx:Breathing problems"
label variable c261c    "Danger signs addl tx:Becomes sicker"
label variable c261d    "Danger signs addl tx:Blood in stool"
label variable c261e    "Danger signs addl tx:Vomiting"
label variable c261f    "Danger signs addl tx:Poor eating/not eating"
label variable c261g    "Danger signs addl tx:Poor drinking/not drinking"
label variable c261h    "NA - Danger signs addl tx:Convulsions"
label variable c261x    "Danger signs addl tx:Other"
label variable c261y    "Danger signs addl tx:No signs"
label variable c261z    "Danger signs addl tx:Don't know"
label variable c262a    "Adv non-emergency return:More medicines"
label variable c262b    "Adv non-emergency return:Symptoms increase or worsen"
label variable c262c    "Adv non-emergency return:Follow-up appointment"
label variable c262d    "Adv non-emergency return:Child admitted"
label variable c262e    "Adv non-emergency return:Routine immunization"
label variable c262f    "NA - Adv non-emergency return:Vitamin A supplementation"
label variable c262g    "NA - Adv non-emergency return:Lab test results"
label variable c262x    "Adv non-emergency return:Other"
label variable c262y    "Adv non-emergency return:No reason"
label variable c262z    "Adv non-emergency return:Don't know"
label variable c263     "Provider gave or prescribed medicines for home use"
label variable c264     "Caretaker has medications/prescriptions"
label variable c265     "Provider explained how to give medications"
label variable c266     "Caretaker feels comfortable about giving medications"
label variable c267     "Child given first dose at facility"
label variable c268     "Child given injection for treatment today"
label variable c270     "Provider asked about types of food given when not sick"
label variable c271     "Child weighed at facility"
label variable c272     "Provider talked about weight and how child is growing"
label variable c274     "Provider advised about feeding solids during illness"
label variable c275     "Provider advised about feeding liquids/breastmilk during illness"
label variable c276     "Child given vaccination"
label variable c280a    "NA - Referral:Caretaker instructed to take child for finger/heel stick to lab or"
label variable c280b    "NA - Referral:Caretaker took child for finger/heel stick"
label variable c280c    "NA - Referral:Caretaker told result of finger/heel stick test"
label variable c280d    "Referral:Caretaker instructed to take child for tests outside facility"
label variable c281a    "Outside referral: Given paper or record to take to referral"
label variable c281b    "Outside referral: Told where to go for referral"
label variable c281c    "Outside referral: Told whom to see for referral"
label variable c281d    "Outside referral: Told why to go for referral"
label variable c281e    "NA - Outside referral: Caretaker intends to go to referral(s)"
label variable c282a    "Provider visited prior to visit: Other provider in this facility"
label variable c282b    "Provider visited prior to visit: Other provider in different facility"
label variable c282c    "Provider visited prior to visit: Traditional healer"
label variable c282y    "Provider visited prior to visit: No other provider"
label variable sxc103d  "CS - Day of birth"
label variable sxc131   "CS - Has vaccination card observed"

#delimit ;
label define C001    
     1 "West"
     2 "Southeast"
     3 "North"
     4 "Northeast"
     5 "Artibonite"
     6 "Central"
     7 "South"
     8 "Grand-Anse"
     9 "Northwest"
    10 "Nippes"
;
label define C003    
     1 "Urban"
     2 "Rural"
;
label define C007    
     1 "University hospital"
     2 "Regional hospital"
     3 "Community referral hospital"
     4 "Hospital"
     5 "Health center with LIT"
     6 "Health center without LIT"
     7 "Dispensary"
;
label define C008    
     1 "Government/public"
     2 "NGO/ Private not for profit"
     3 "Private for profit"
     4 "Mission/ faith-based"
;
label define C020A   
     0 "Refused by provider or client"
     1 "Complete"
     7 "Not returned from field"
;
label define C020B   
     0 "Refused by client"
     1 "Complete"
     2 "Sick child admitted, not possible to continue"
     7 "Not returned from field"
;
label define C021    
     1 "ANC"
     2 "Child Sick"
     3 "Family Planning"
     6 "CS - Labor/Delivery"
;
label define C022    
     1 "Male"
     2 "Female"
;
label define C023    
     1 "Male"
     2 "Female"
;
label define C024    
     1 "Medical doctor (generalist)"
     2 "Surgeon (general)"
     3 "Medical specialist"
    21 "Nurse"
    22 "Nurse/midwife"
    23 "Auxiliary nurse"
    35 "Lab technician, medical technologist"
    71 "Auxiliary dentist"
    72 "Other community health workers"
    95 "Non-technical qualification"
    96 "Other"
;
label define C501    
     0 "Saw provider immediately"
   998 "Don't know"
;
label define C502A   
     0 "No problem"
     1 "Large problem"
     2 "Small problem"
     8 "Don't know"
;
label define C502B   
     0 "No problem"
     1 "Large problem"
     2 "Small problem"
     8 "Don't know"
;
label define C502C   
     0 "No problem"
     1 "Large problem"
     2 "Small problem"
     8 "Don't know"
;
label define C502E   
     0 "No problem"
     1 "Large problem"
     2 "Small problem"
     8 "Don't know"
;
label define C502F   
     0 "No problem"
     1 "Large problem"
     2 "Small problem"
     8 "Don't know"
;
label define C502G   
     0 "No problem"
     1 "Large problem"
     2 "Small problem"
     8 "Don't know"
;
label define C502H   
     0 "No problem"
     1 "Large problem"
     2 "Small problem"
     8 "Don't know"
;
label define C502I   
     0 "No problem"
     1 "Large problem"
     2 "Small problem"
     8 "Don't know"
;
label define C502J   
     0 "No problem"
     1 "Large problem"
     2 "Small problem"
     8 "Don't know"
;
label define C502K   
     0 "No problem"
     1 "Large problem"
     2 "Small problem"
     8 "Don't know"
;
label define C502L   
     0 "No problem"
     1 "Large problem"
     2 "Small problem"
     8 "Don't know"
;
label define C503    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define C504    
     0 "No"
     1 "Yes"
;
label define C505    
999998 "Don't know"
;
label define C507    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define C508    
     1 "Inconvenient operating hours"
     2 "Bad reputation"
     3 "Don't like personnel"
     4 "No medicine"
     5 "Prefers to remain anonymous"
     6 "More expensive"
     7 "Referral"
    96 "Other"
    98 "Don't know"
;
label define C510    
     1 "Mother"
     2 "Father"
     3 "Sibling"
     4 "Aunt or uncle"
     5 "Grandparent"
     6 "Other"
;
label define C511    
    98 "Don't know"
;
label define C512    
     0 "Never attended school"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
;
label define C514    
     0 "Cannot read or write"
     1 "Read only"
     2 "Read and write"
     8 "Don;t know"
;
label define C515    
     0 "No schooling"
     1 "Primary"
     2 "Post primary/technical"
     3 "Secondary"
     4 "Higher/University"
;
label define C517A   
  9797 "Inconsistent"
  9898 "Don't know"
;
label define C517B   
  9797 "Inconsistent"
  9898 "Don't know"
;
label define C518A   
  9797 "Inconsistent"
  9898 "Don't know"
;
label define C518B   
  9797 "Inconsistent"
  9898 "Don't know"
;
label define C520    
     1 "Very satisfied"
     2 "Somewhat satisfied"
     3 "Not satisfied"
;
label define C521    
     0 "No"
     1 "Yes"
     8 "DK"
;
label define C522    
     0 "No or incomplete observation"
     1 "Yes"
     2 "More than 1 reported as first"
;
label define SCDEPART
     0 "West Metropolitan"
     1 "Other west"
     2 "Southeast"
     3 "North"
     4 "Northeast"
     5 "Artibonite"
     6 "Central"
     7 "South"
     8 "Grand-Anse"
     9 "Northwest"
    10 "Nippes"
;
label define SCLOCAL 
     1 "Metropolitan"
     2 "Other urban"
     3 "Rural"
;
label define C202    
     1 "First visit"
     2 "Follow-up visit"
     8 "Don't know"
;
label define C203A   
     0 "No"
     1 "Yes"
;
label define C203B   
     0 "No"
     1 "Yes"
;
label define C203C   
     0 "No"
     1 "Yes"
;
label define C203D   
     0 "No"
     1 "Yes"
;
label define C203Y   
     0 "No"
     1 "Yes, no main symptoms"
;
label define C204A   
     0 "No"
     1 "Yes"
;
label define C204B   
     0 "No"
     1 "Yes"
;
label define C204C   
     0 "No"
     1 "Yes"
;
label define C204D   
     0 "No"
     1 "Yes"
;
label define C204E   
     0 "No"
     1 "Yes"
;
label define C204F   
     0 "No"
     1 "Yes"
;
label define C204Y1  
     0 "No"
     1 "Yes, none of general danger signs"
;
label define C204Y2  
     0 "No"
     1 "Yes, none of HIV symptomatic indicators"
;
label define C205A   
     0 "No"
     1 "Yes"
;
label define C205B   
     0 "No"
     1 "Yes"
;
label define C205C   
     0 "No"
     1 "Yes"
;
label define C205D   
     0 "No"
     1 "Yes"
;
label define C205E   
     0 "No"
     1 "Yes"
;
label define C205F   
     0 "No"
     1 "Yes"
;
label define C205G   
     0 "No"
     1 "Yes"
;
label define C205H   
     0 "No"
     1 "Yes"
;
label define C205I   
     0 "No"
     1 "Yes"
;
label define C205J   
     0 "No"
     1 "Yes"
;
label define C205K   
     0 "No"
     1 "Yes"
;
label define C205M   
     0 "No"
     1 "Yes"
;
label define C205N   
     0 "No"
     1 "Yes"
;
label define C205P   
     0 "No"
     1 "Yes"
;
label define C205Q   
     0 "No"
     1 "Yes"
;
label define C205R   
     0 "No"
     1 "Yes"
;
label define C205S   
     0 "No"
     1 "Yes"
;
label define C205Y   
     0 "No"
     1 "Yes, none"
;
label define CF205A  
     0 "Activity not routinely done"
     1 "Observed"
     2 "Reported, not seen"
     8 "Don't know"
;
label define CF205M  
     0 "Activity not routinely done"
     1 "Observed"
     2 "Reported, not seen"
     8 "Don't know"
;
label define CF205N  
     0 "Activity not routinely done"
     1 "Observed"
     2 "Reported, not seen"
     8 "Don't know"
;
label define CF205XA 
     0 "Activity not routinely done"
     1 "Observed"
     2 "Reported, not seen"
     8 "Don't know"
;
label define CF205XB 
     0 "Activity not routinely done"
     1 "Observed"
     2 "Reported, not seen"
     8 "Don't know"
;
label define CF205XC 
     0 "Activity not routinely done"
     1 "Observed"
     2 "Reported, not seen"
     8 "Don't know"
;
label define CF205XD 
     0 "Activity not routinely done"
     1 "Observed"
     2 "Reported, not seen"
     8 "Don't know"
;
label define CF205XE 
     0 "Activity not routinely done"
     1 "Observed"
     2 "Reported, not seen"
     8 "Don't know"
;
label define C206A   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define C206B   
     0 "No"
     1 "Yes"
;
label define C206C   
     0 "No"
     1 "Yes"
;
label define C206D   
     0 "No"
     1 "Yes"
;
label define C206E   
     0 "No"
     1 "Yes"
;
label define C206F   
     0 "No"
     1 "Yes"
;
label define C206G   
     0 "No"
     1 "Yes"
;
label define C206I   
     0 "No"
     1 "Yes"
;
label define C206Y   
     0 "No"
     1 "Yes, none"
;
label define C207A   
     0 "No"
     1 "Yes"
;
label define C207B   
     0 "No"
     1 "Yes"
;
label define C207C   
     0 "No"
     1 "Yes"
;
label define C207D   
     0 "No"
     1 "Yes"
;
label define C207E   
     0 "No"
     1 "Yes"
;
label define C207F   
     0 "No"
     1 "Yes"
;
label define C207Y   
     0 "No"
     1 "Yes, none"
;
label define C208B   
     0 "No"
     1 "Yes"
;
label define C208C   
     0 "No"
     1 "Yes"
;
label define C208D   
     0 "No"
     1 "Yes"
;
label define C208E   
     0 "No"
     1 "Yes"
;
label define C208F   
     0 "No"
     1 "Yes"
;
label define C208G   
     0 "No"
     1 "Yes"
;
label define C208H   
     0 "No"
     1 "Yes"
;
label define C208Y   
     0 "No"
     1 "Yes, none"
;
label define C209A   
     0 "No"
     1 "Yes"
;
label define C209B   
     0 "No"
     1 "Yes"
;
label define C209C   
     0 "No"
     1 "Yes"
;
label define C209D   
     0 "No"
     1 "Yes"
;
label define C209Y   
     0 "No"
     1 "Yes, none"
;
label define C211A   
     0 "No"
     1 "Yes"
;
label define C211B   
     0 "No"
     1 "Yes"
;
label define C212    
     0 "No"
     1 "Yes"
;
label define C213    
     1 "Child sent home"
     2 "Child referred to provider at same facility"
     3 "Child admitted to same facility"
     4 "Child sent to lab"
     5 "Child referred to other facility"
;
label define C220    
     1 "Yes, all with responses"
;
label define C221A   
     0 "No"
     1 "Yes, severity not reported"
;
label define C221C   
     0 "No"
     1 "Yes, severity not reported"
;
label define C221D   
     0 "No"
     1 "Yes, severity not reported"
;
label define C221E   
     0 "No"
     1 "Yes, severity not reported"
;
label define C221F   
     0 "No"
     1 "Yes, severity not reported"
;
label define C221Y   
     0 "No"
     1 "Yes, no respiratory dx"
;
label define C222A   
     0 "No"
     1 "Yes, severity not reported"
;
label define C222B   
     0 "No"
     1 "Yes, severity not reported"
;
label define C222C   
     0 "No"
     1 "Yes, severity not reported"
;
label define C222D   
     0 "No"
     1 "Yes, severity not reported"
;
label define C222E   
     0 "No"
     1 "Yes, severity not reported"
;
label define C222F   
     0 "No"
     1 "Yes, severity not reported"
;
label define C222Y   
     0 "No"
     1 "Yes, no digestive dx"
;
label define C223A   
     0 "No"
     1 "Severe"
     2 "Moderate"
     3 "Mild"
     8 "Don't know"
;
label define C224A   
     0 "No"
     1 "Yes, severity not reported"
;
label define C224B   
     0 "No"
     1 "Yes, severity not reported"
;
label define C224D   
     0 "No"
     1 "Yes, severity not reported"
;
label define C224Y   
     0 "No"
     1 "Yes, no malaria dx"
;
label define C225A   
     0 "No"
     1 "Yes, severity not reported"
;
label define C225B   
     0 "No"
     1 "Yes, severity not reported"
;
label define C225C   
     0 "No"
     1 "Yes, severity not reported"
;
label define C225D   
     0 "No"
     1 "Yes, severity not reported"
;
label define C225E   
     0 "No"
     1 "Yes, severity not reported"
;
label define C225F   
     0 "No"
     1 "Yes, severity not reported"
;
label define C225G   
     0 "No"
     1 "Yes, severity not reported"
;
label define C225Y   
     0 "No"
     1 "Yes, no fever/measles dx"
;
label define C226A   
     0 "No"
     1 "Yes, severity not reported"
;
label define C226B   
     0 "No"
     1 "Yes, severity not reported"
;
label define C226C   
     0 "No"
     1 "Yes, severity not reported"
;
label define C226D   
     0 "No"
     1 "Yes, severity not reported"
;
label define C226Y   
     0 "No"
     1 "Yes, no ear dx"
;
label define C227A   
     0 "No"
     1 "Yes, severity not reported"
;
label define C227B   
     0 "No"
     1 "Yes, severity not reported"
;
label define C227C   
     0 "No"
     1 "Yes, severity not reported"
;
label define C227D   
     0 "No"
     1 "Yes, severity not reported"
;
label define C227Y   
     0 "No"
     1 "Yes, no throat dx"
;
label define C228A   
     0 "No"
     1 "Yes, severity not reported"
;
label define C228B   
     0 "No"
     1 "Yes, severity not reported"
;
label define C228C   
     0 "No"
     1 "Yes, severity not reported"
;
label define C228D   
     0 "No"
     1 "Yes, severity not reported"
;
label define C228Y   
     0 "No"
     1 "Yes, no other dx"
;
label define C230_36Y
     0 "No, some treatment prescribed"
     1 "Yes, no treatment prescribed during visit"
;
label define C230A   
     0 "No"
     1 "Yes"
;
label define C230B   
     0 "No"
     1 "Yes"
;
label define C230C   
     0 "No"
     1 "Yes"
;
label define C230E   
     0 "No"
     1 "Yes"
;
label define C230F   
     0 "No"
     1 "Yes"
;
label define C230G   
     0 "No"
     1 "Yes"
;
label define C230H   
     0 "No"
     1 "Yes"
;
label define C230I   
     0 "No"
     1 "Yes"
;
label define C230J   
     0 "No"
     1 "Yes"
;
label define C230K   
     0 "No"
     1 "Yes"
;
label define C230L   
     0 "No"
     1 "Yes"
;
label define C230M   
     0 "No"
     1 "Yes"
;
label define C230N   
     0 "No"
     1 "Yes"
;
label define C230Y   
     0 "No"
     1 "Yes, no general med given"
;
label define C232A   
     0 "No"
     1 "Yes"
;
label define C232B   
     0 "No"
     1 "Yes"
;
label define C232C   
     0 "No"
     1 "Yes"
;
label define C232D   
     0 "No"
     1 "Yes"
;
label define C232Y   
     0 "No"
     1 "Yes, no respiratory med given"
;
label define C233A   
     0 "No"
     1 "Yes"
;
label define C233C   
     0 "No"
     1 "Yes"
;
label define C233E   
     0 "No"
     1 "Yes"
;
label define C233F   
     0 "No"
     1 "Yes"
;
label define C234A   
     0 "No"
     1 "Yes"
;
label define C234B   
     0 "No"
     1 "Yes"
;
label define C234C   
     0 "No"
     1 "Yes"
;
label define C234D   
     0 "No"
     1 "Yes"
;
label define C234E   
     0 "No"
     1 "Yes"
;
label define C234F   
     0 "No"
     1 "Yes"
;
label define C234G   
     0 "No"
     1 "Yes"
;
label define C234H   
     0 "No"
     1 "Yes"
;
label define C234X   
     0 "No"
     1 "Yes"
;
label define C234Y   
     0 "No"
     1 "Yes, no malaria medication given"
;
label define C235A   
     0 "No"
     1 "Yes"
;
label define C235B   
     0 "No"
     1 "Yes"
;
label define C235C   
     0 "No"
     1 "Yes"
;
label define C235Y   
     0 "No"
     1 "Yes, no dehydration tx given"
;
label define C236A   
     0 "No"
     1 "Yes"
;
label define C236B   
     0 "No"
     1 "Yes"
;
label define C236C   
     0 "No"
     1 "Yes"
;
label define C236D   
     0 "No"
     1 "Yes"
;
label define C236E   
     0 "No"
     1 "Yes"
;
label define C236X   
     0 "No"
     1 "Yes"
;
label define C236Y   
     0 "No"
     1 "Yes, no other treatment/ advice"
;
label define C238    
     0 "No"
     1 "Yes, given"
     2 "Yes, referred"
;
label define C239    
     1 "Not due for immunization"
     2 "Vaccine not available"
     3 "Child too sick"
     4 "Not day for immunization"
     5 "Did not check for immunization"
     6 "Completed immunization schedule"
    96 "Other"
;
label define C250    
  9999 "Missing"
;
label define C251    
    99 "Missing"
;
label define C252    
  9999 "Missing"
;
label define C253    
    99 "Missing"
;
label define C254    
     1 "Fully specified date"
     2 "Year given"
     3 "Age given"
     6 "No information"
;
label define C255A   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define C255B   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define C255C   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define C255D   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define C255E   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define C255F   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define C255G   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define C256A   
     0 "No"
     1 "Yes"
;
label define C256B   
     0 "No"
     1 "Yes"
;
label define C256C   
     0 "No"
     1 "Yes"
;
label define C256D   
     0 "No"
     1 "Yes"
;
label define C256X   
     0 "No"
     1 "Yes"
;
label define C256Y   
     0 "No"
     1 "Yes, no other reason for visit"
;
label define C257    
     0 "No"
     1 "Yes,within past week"
     2 "Yes,within past 2-4 weeks"
     3 "Yes,more than 4 weeks ago"
     4 "Yes,don't know when"
     8 "Don't know if other visits"
;
label define C258    
    98 "Don't know"
;
label define C259    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define C260    
     1 "Return to facility"
     2 "Go to other facility"
     3 "Go to other health worker/pharmacy"
     4 "Go to traditional healer"
     5 "Wait"
     6 "Other"
     8 "Don't know"
;
label define C261A   
     0 "No"
     1 "Yes"
;
label define C261B   
     0 "No"
     1 "Yes"
;
label define C261C   
     0 "No"
     1 "Yes"
;
label define C261D   
     0 "No"
     1 "Yes"
;
label define C261E   
     0 "No"
     1 "Yes"
;
label define C261F   
     0 "No"
     1 "Yes"
;
label define C261G   
     0 "No"
     1 "Yes"
;
label define C261H   
     0 "No"
     1 "Yes"
;
label define C261X   
     0 "No"
     1 "Yes"
;
label define C261Y   
     0 "No"
     1 "Yes, no sign"
;
label define C261Z   
     0 "No"
     1 "Yes, don't know"
;
label define C262A   
     0 "No"
     1 "Yes"
;
label define C262B   
     0 "No"
     1 "Yes"
;
label define C262C   
     0 "No"
     1 "Yes"
;
label define C262D   
     0 "No"
     1 "Yes"
;
label define C262E   
     0 "No"
     1 "Yes"
;
label define C262F   
     0 "No"
     1 "Yes"
;
label define C262G   
     0 "No"
     1 "Yes"
;
label define C262X   
     0 "No"
     1 "Yes"
;
label define C262Y   
     0 "No"
     1 "Yes. no non-emergency return"
;
label define C262Z   
     0 "No"
     1 "Yes, don't know"
;
label define C263    
     0 "No"
     1 "Yes, gave medications"
     2 "Yes, gave prescription"
     3 "Yes, gave medications and prescriptions"
;
label define C264    
     0 "Has no medications, only prescriptions"
     1 "Has all medications"
     2 "Has some medications and some unfilled prescriptions"
;
label define C265    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define C266    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define C267    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define C268    
     0 "No"
     1 "Yes, received injection"
     2 "Yes, received prescription for injection"
     8 "Don't know"
;
label define C270    
     0 "No"
     1 "Yes"
     8 "Can't remember"
;
label define C271    
     0 "No"
     1 "Yes"
;
label define C272    
     0 "No"
     1 "Yes"
;
label define C274    
     0 "Didn't discuss"
     1 "Give less than usual"
     2 "Give same as usual"
     3 "Give more than usual"
     4 "Give nothing/don't feed solids"
     8 "Not certain"
;
label define C275    
     0 "Didn't discuss"
     1 "Give less than usual"
     2 "Give same as usual"
     3 "Give more than usual"
     4 "Give nothing/don't feed fluids/breastmilk"
     8 "Not certain"
;
label define C276    
     0 "No"
     1 "Yes, observed"
     2 "Reported, not seen"
     8 "Don't know"
;
label define C280A   
     0 "No"
     1 "Yes"
;
label define C280B   
     0 "No"
     1 "Yes"
;
label define C280C   
     0 "No"
     1 "Yes"
;
label define C280D   
     0 "No"
     1 "Yes"
;
label define C281A   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define C281B   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define C281C   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define C281D   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define C281E   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define C282A   
     0 "No"
     1 "Yes"
;
label define C282B   
     0 "No"
     1 "Yes"
;
label define C282C   
     0 "No"
     1 "Yes"
;
label define C282Y   
     0 "No"
     1 "Yes, saw no one"
;
label define SXC103D 
    98 "Don't know"
;
label define SXC131  
     0 "No"
     1 "Yes, date of visit observed"
     2 "Yes, but no date for vacc given on day of visit"
;

#delimit cr
label values c001     C001    
label values c003     C003    
label values c007     C007    
label values c008     C008    
label values c020a    C020A   
label values c020b    C020B   
label values c021     C021    
label values c022     C022    
label values c023     C023    
label values c024     C024    
label values c501     C501    
label values c502a    C502A   
label values c502b    C502B   
label values c502c    C502C   
label values c502e    C502E   
label values c502f    C502F   
label values c502g    C502G   
label values c502h    C502H   
label values c502i    C502I   
label values c502j    C502J   
label values c502k    C502K   
label values c502l    C502L   
label values c503     C503    
label values c504     C504    
label values c505     C505    
label values c507     C507    
label values c508     C508    
label values c510     C510    
label values c511     C511    
label values c512     C512    
label values c514     C514    
label values c515     C515    
label values c517a    C517A   
label values c517b    C517B   
label values c518a    C518A   
label values c518b    C518B   
label values c520     C520    
label values c521     C521    
label values c522     C522    
label values scdepart SCDEPART
label values sclocal  SCLOCAL 
label values c202     C202    
label values c203a    C203A   
label values c203b    C203B   
label values c203c    C203C   
label values c203d    C203D   
label values c203y    C203Y   
label values c204a    C204A   
label values c204b    C204B   
label values c204c    C204C   
label values c204d    C204D   
label values c204e    C204E   
label values c204f    C204F   
label values c204y1   C204Y1  
label values c204y2   C204Y2  
label values c205a    C205A   
label values c205b    C205B   
label values c205c    C205C   
label values c205d    C205D   
label values c205e    C205E   
label values c205f    C205F   
label values c205g    C205G   
label values c205h    C205H   
label values c205i    C205I   
label values c205j    C205J   
label values c205k    C205K   
label values c205m    C205M   
label values c205n    C205N   
label values c205p    C205P   
label values c205q    C205Q   
label values c205r    C205R   
label values c205s    C205S   
label values c205y    C205Y   
label values cf205a   CF205A  
label values cf205m   CF205M  
label values cf205n   CF205N  
label values cf205xa  CF205XA 
label values cf205xb  CF205XB 
label values cf205xc  CF205XC 
label values cf205xd  CF205XD 
label values cf205xe  CF205XE 
label values c206a    C206A   
label values c206b    C206B   
label values c206c    C206C   
label values c206d    C206D   
label values c206e    C206E   
label values c206f    C206F   
label values c206g    C206G   
label values c206i    C206I   
label values c206y    C206Y   
label values c207a    C207A   
label values c207b    C207B   
label values c207c    C207C   
label values c207d    C207D   
label values c207e    C207E   
label values c207f    C207F   
label values c207y    C207Y   
label values c208b    C208B   
label values c208c    C208C   
label values c208d    C208D   
label values c208e    C208E   
label values c208f    C208F   
label values c208g    C208G   
label values c208h    C208H   
label values c208y    C208Y   
label values c209a    C209A   
label values c209b    C209B   
label values c209c    C209C   
label values c209d    C209D   
label values c209y    C209Y   
label values c211a    C211A   
label values c211b    C211B   
label values c212     C212    
label values c213     C213    
label values c220     C220    
label values c221a    C221A   
label values c221c    C221C   
label values c221d    C221D   
label values c221e    C221E   
label values c221f    C221F   
label values c221y    C221Y   
label values c222a    C222A   
label values c222b    C222B   
label values c222c    C222C   
label values c222d    C222D   
label values c222e    C222E   
label values c222f    C222F   
label values c222y    C222Y   
label values c223a    C223A   
label values c224a    C224A   
label values c224b    C224B   
label values c224d    C224D   
label values c224y    C224Y   
label values c225a    C225A   
label values c225b    C225B   
label values c225c    C225C   
label values c225d    C225D   
label values c225e    C225E   
label values c225f    C225F   
label values c225g    C225G   
label values c225y    C225Y   
label values c226a    C226A   
label values c226b    C226B   
label values c226c    C226C   
label values c226d    C226D   
label values c226y    C226Y   
label values c227a    C227A   
label values c227b    C227B   
label values c227c    C227C   
label values c227d    C227D   
label values c227y    C227Y   
label values c228a    C228A   
label values c228b    C228B   
label values c228c    C228C   
label values c228d    C228D   
label values c228y    C228Y   
label values c230_36y C230_36Y
label values c230a    C230A   
label values c230b    C230B   
label values c230c    C230C   
label values c230e    C230E   
label values c230f    C230F   
label values c230g    C230G   
label values c230h    C230H   
label values c230i    C230I   
label values c230j    C230J   
label values c230k    C230K   
label values c230l    C230L   
label values c230m    C230M   
label values c230n    C230N   
label values c230y    C230Y   
label values c232a    C232A   
label values c232b    C232B   
label values c232c    C232C   
label values c232d    C232D   
label values c232y    C232Y   
label values c233a    C233A   
label values c233c    C233C   
label values c233e    C233E   
label values c233f    C233F   
label values c234a    C234A   
label values c234b    C234B   
label values c234c    C234C   
label values c234d    C234D   
label values c234e    C234E   
label values c234f    C234F   
label values c234g    C234G   
label values c234h    C234H   
label values c234x    C234X   
label values c234y    C234Y   
label values c235a    C235A   
label values c235b    C235B   
label values c235c    C235C   
label values c235y    C235Y   
label values c236a    C236A   
label values c236b    C236B   
label values c236c    C236C   
label values c236d    C236D   
label values c236e    C236E   
label values c236x    C236X   
label values c236y    C236Y   
label values c238     C238    
label values c239     C239    
label values c254     C254    
label values c255a    C255A   
label values c255b    C255B   
label values c255c    C255C   
label values c255d    C255D   
label values c255e    C255E   
label values c255f    C255F   
label values c255g    C255G   
label values c256a    C256A   
label values c256b    C256B   
label values c256c    C256C   
label values c256d    C256D   
label values c256x    C256X   
label values c256y    C256Y   
label values c257     C257    
label values c258     C258    
label values c259     C259    
label values c260     C260    
label values c261a    C261A   
label values c261b    C261B   
label values c261c    C261C   
label values c261d    C261D   
label values c261e    C261E   
label values c261f    C261F   
label values c261g    C261G   
label values c261h    C261H   
label values c261x    C261X   
label values c261y    C261Y   
label values c261z    C261Z   
label values c262a    C262A   
label values c262b    C262B   
label values c262c    C262C   
label values c262d    C262D   
label values c262e    C262E   
label values c262f    C262F   
label values c262g    C262G   
label values c262x    C262X   
label values c262y    C262Y   
label values c262z    C262Z   
label values c263     C263    
label values c264     C264    
label values c265     C265    
label values c266     C266    
label values c267     C267    
label values c268     C268    
label values c270     C270    
label values c271     C271    
label values c272     C272    
label values c274     C274    
label values c275     C275    
label values c276     C276    
label values c280a    C280A   
label values c280b    C280B   
label values c280c    C280C   
label values c280d    C280D   
label values c281a    C281A   
label values c281b    C281B   
label values c281c    C281C   
label values c281d    C281D   
label values c281e    C281E   
label values c282a    C282A   
label values c282b    C282B   
label values c282c    C282C   
label values c282y    C282Y   
label values sxc103d  SXC103D 
label values sxc131   SXC131  
