infix using "C:\NEWSPA_AUG30\HT6A\EXPORT\EXPORTEDFILES\HTAN6AFLSR.dct"

label variable inv_id   "INVENTORY ID"
label variable p_id     "Unit/Provider line number ID"
label variable obs_n    "Client type code"
label variable obs_id   "Client ID"
label variable c000     "Survey phase"
label variable c001     "Region (Country-specific)"
label variable c002     "District (Country-specific)"
label variable c003     "Urban/rural"
label variable c004     "Facility number"
label variable c004p    "Provider line number"
label variable c004ct   "Client type code (alpha)"
label variable c004cn   "Client ID number"
label variable c005     "Sample weight"
label variable c007     "Facility type (Country-specific)"
label variable c008     "Operating Authority (Country-specific)"
label variable c009a    "Interviewer for observation"
label variable c009b    "Interviewer for exit interview"
label variable c009c    "NA - Keyer"
label variable c020a    "Result of observation"
label variable c020b    "Result of exit intervIew"
label variable c021     "Type of client"
label variable c022     "Sex of provider"
label variable c023     "Sex of client/sick child"
label variable c024     "Technical qualification of provider (Country-specific within ranges)"
label variable c032     "Month of observation/interview"
label variable c033     "Year of observation/interview"
label variable c033d    "Day of observation/interview"
label variable c501     "Duration of wait before being seen (in minutes)"
label variable c502a    "Client problem during visit:Time had to wait"
label variable c502b    "Client problem during visit:Ability to discuss problems/concerns"
label variable c502c    "Client problem during visit:Amount of explanation for problem/tx"
label variable c502e    "Client problem during visit:Visual privacy"
label variable c502f    "Client problem during visit:Auditory privacy"
label variable c502g    "Client problem during visit:Availability of medicines at facility"
label variable c502h    "Client problem during visit:Hours of service"
label variable c502i    "Client problem during visit:Days of service"
label variable c502j    "Client problem during visit:Cleanliness of facility"
label variable c502k    "Client problem during visit:Staff treatment of client"
label variable c502l    "Client problem during visit:Cost"
label variable c503     "Part of prepayment plan/insurance that pays part of cost"
label variable c504     "Charged for services today"
label variable c505     "Total amount paid (in gourdes)"
label variable c507     "Facility nearest to home"
label variable c508     "Reason did not go to nearest facility"
label variable c510     "Caretaker relationship to sick child (Sick child exit only)"
label variable c511     "Age of client (caretaker of client)"
label variable c512     "Highest level of education attended"
label variable c514     "Literacy level"
label variable c515     "Country reported highest level of education attended (CS)"
label variable c517a    "Time observation interview began"
label variable c517b    "Time observation interview ended"
label variable c518a    "Time exit interview began"
label variable c518b    "Time exit interview ended"
label variable c520     "Opinion of services given today"
label variable c521     "Would recommend to friend/family member"
label variable c522     "First observation for this provider for this service"
label variable scdepart "CS - Region with West separated for metropolitan and other"
label variable sclocal  "Metropoliltan/other urban/rural"
label variable c101a    "Number of visits to this facility for this pregnancy (OBSERVATION only)"
label variable c101f    "Flag: Consistency of visit number: observation and exit (C155)"
label variable c102     "Client first pregnancy  (OBSERVATION only)"
label variable c102f    "Flag: Consistency of first pregnancy:observation and exit (C154)"
label variable c103a    "Client history information provided: Age"
label variable c103b    "Client history information provided: Current medications"
label variable c103c    "Client history information provided: Date last menstrual period began"
label variable c103d    "Client history information provided: Number of prior pregnancies"
label variable c103y    "Client history information provided: No history mentioned"
label variable c104a    "Client prior pregnancy :Prior stillbirth(s)"
label variable c104b    "Client prior pregnancy:Infants who died in first week"
label variable c104c    "Client prior pregnancy:Heavy bleeding during or after delivery"
label variable c104d    "Client prior pregnancy:Previous assisted delivery"
label variable c104e    "Client prior pregnancy:Previous spontaneous abortions"
label variable c104f    "Client prior pregnancy Multiple pregnancies"
label variable c104g    "Client prior pregnancy:Prolonged labor"
label variable c104h    "Client prior pregnancy:Pregnancy-induced hypertension"
label variable c104i    "Client prior pregnancy:Pregnancy related convulsions"
label variable c104j    "Client prior pregnancy:High fever or infection during prior pregnancy/pregnancie"
label variable c104k    "CS - Client prior pregnancy:Infants who died in first 4 weeks of life"
label variable c104y    "Client prior pregnancy:No aspects of prior pregnancies mentioned"
label variable c105a    "Provider/client asked about danger sign:Bleeding"
label variable c105b    "Provider/client asked about danger sign:Fever"
label variable c105c    "Provider/client asked about danger sign:Headache or blurred vision"
label variable c105d    "Provider/client asked about danger sign:Swollen face, hands or extremities"
label variable c105e    "Provider/client asked about danger sign:Tiredness or breathlessness"
label variable c105f    "Provider/client asked about danger sign:Fetal movement (loss of, excessive, norm"
label variable c105g    "Provider/client asked about danger sign:Any other symptoms or problems in pregna"
label variable c105h    "Provider/client asked about danger sign:Cough or difficulty breathing for 3 week"
label variable c105x    "Provider/client asked about danger sign:Other problems client believes related t"
label variable c105y    "Provider/client asked about danger sign:No danger signs of current pregnancy men"
label variable c105a1   "Provider counseled danger sign:Bleeding"
label variable c105b1   "Provider counseled danger sign:Fever"
label variable c105c1   "Provider counseled danger sign:Headache or blurred vision"
label variable c105d1   "Provider counseled danger sign:Swollen face, hands or extremities"
label variable c105e1   "Provider counseled danger sign:Tiredness or breathlessness"
label variable c105f1   "Provider counseled danger sign:Fetal movement (loss of, excessive, normal)"
label variable c105g1   "Provider counseled danger sign:Any other symptoms or problems in pregnancy"
label variable c105h1   "Provider counseled danger sign:Cough or difficulty breathing for 3 weeks or long"
label variable c105x1   "Provider counseled danger sign:Other problems client believes related to pregnan"
label variable c105y1   "Provider counseled danger sign:No danger signs of current pregnancy counseled"
label variable c106a    "Procedures performed:Blood pressure"
label variable c106b    "Procedures performed:Palpate abdomen for fetal presentation"
label variable c106c    "Procedures performed:Palpate abdomen for fetal height"
label variable c106d    "Procedures performed:Listen to abdomen for fetal heartbeat"
label variable c106k    "Procedures performed:Weigh client"
label variable c106l    "Procedures performed:Examine conjunctiva/palms for anemia"
label variable c106m    "Procedures performed:Examine legs/feet/hands for edema"
label variable c106n    "Procedures performed:Examine client's breasts"
label variable c106o    "Procedures performed:Conduct vaginal exam/exam of perineal area"
label variable c106p    "Procedures performed:Examine for swollen glands"
label variable c106q    "Procedures performed:Conduct/refer ultrasound or look at ultrasound report"
label variable c106r    "NA - Procedures performed:Measure fundal height with a tape measure"
label variable c106y    "Procedures performed:None of physical exam components"
label variable cf106a   "Routine action in facility: Blood pressure"
label variable cf106k   "Routine action in facility: Weigh client"
label variable cf106xa  "Routine action in facility: Conduct group health education"
label variable cf106xb  "Routine action in facility: Urine test for protein"
label variable cf106xc  "Routine action in facility: Blood test for anemia"
label variable cf106xd  "NA - Routine action in facility: Malaria RDT"
label variable cf106xe  "NA - Routine action in facility: HIV testing and counseling"
label variable cf106xf  "NA - CS Routine action in facility:"
label variable cf106xg  "NA - CS Routine action in facility:"
label variable c107a    "Provider treatments or counsel:Prescribe/give iron, folic acid or both"
label variable c107b    "Provider treatments or counsel:Explain purpose of iron/folic acid"
label variable c107c    "Provider treatments or counsel:Explain how to take iron/folic acid tablets"
label variable c107d    "Provider treatments or counsel:Explain side effects of iron tablets"
label variable c107e    "Provider treatments or counsel:Prescribe or give tetanus toxoid injection"
label variable c107f    "Provider treatments or counsel:Explain purpose of tetanus toxoid"
label variable c107p    "Provider treatments or counsel:Prescribe or give deworming medication"
label variable c107q    "Provider treatments or counsel:Explain purpose of deworming medication"
label variable c107y1   "Provider treatments or counsel:No Iron Prophylaxis components"
label variable c107y2   "Provider treatments or counsel:No Tetanus Toxoid components"
label variable c107y3   "Provider treatments or counsel:No Deworming components"
label variable c108     "Provider discussed quantity/quality of food eaten during pregnancy"
label variable c110     "Provider informed client about progress of pregnancy"
label variable c111     "Provider discussed importance of at least 4 ANC visits"
label variable c111a    "Provider advised/counsel about delivery:Asked client where she will deliver"
label variable c111b    "Provider advised/counsel about delivery:Use skilled healthworker for delivery"
label variable c111c    "Provider advised/counsel about delivery:Items to have for home delivery"
label variable c111e    "Provider advised/counsel about delivery:Advised to prepare for delivery"
label variable c113     "Provider discussed use of family planning after delivery"
label variable c114     "Provider asked if client had any questions/encouraged questions"
label variable c115     "Provider used visual aids during consult"
label variable c116a    "Provider looked at client health card"
label variable c116     "Provider wrote on client health card"
label variable c117     "Weeks of pregnancy according to provider"
label variable c117f    "Flag: Consistency of weeks of pregnancy in observation and exit (C152)"
label variable c118     "Outcome of consult"
label variable c119a    "Routine tests:Perform or refer for anemia (hemoglobin) test"
label variable c119b    "Routine tests:Perform or refer for urine test"
label variable c119c    "Routine tests:Perform or refer for syphilis test"
label variable c119d    "Routine tests:Perform or refer for blood grouping"
label variable c119y    "Routine tests:Perform or refer for no test"
label variable c120a    "HIV counsel/test:Ask if client knows HIV status"
label variable c120b    "HIV counsel/test:Provide counseling related to HIV test"
label variable c120c    "HIV counsel/test:Refer for counseling related to HIV test"
label variable c120d    "HIV counsel/test:Perform HIV test"
label variable c120e    "HIV counsel/test:Refer for HIV test"
label variable c120y    "HIV counsel/test:No HIV counsel/test"
label variable c121a    "NA - Malaria:Gave malaria prophylaxis medicine (SP) during consult"
label variable c121b    "NA - Malaria:Prescribed malaria prophylaxis medicine (SP) for client to obtain e"
label variable c121c    "Malaria:Explain purpose of preventative anti-malarial"
label variable c121d    "NA - Malarial:Explain how to take anti-malarial"
label variable c121e    "Malaria:Explain possible side effects of anti-malarial"
label variable c121f    "NA - Malaria:Observed 1st dose of IPT taken in presence of provider"
label variable c121g    "NA - Malaria:Importance of further doses of IPT explained"
label variable c121h    "NA - Malaria:Provided ITN to client or instructed client to obtain ITN elsewhere"
label variable c121i    "Malaria:Explicitly explained importance of using ITN"
label variable c121y    "Malaria:No components of malaria prevention/protection mentioned"
label variable c122a    "Newborn recommendations:Care of newborn (warmth, hygiene, etc)"
label variable c122b    "Newborn recommendations:Early initiation and prolonged breastfeeding"
label variable c122c    "Newborn recommendations:Exclusive breastfeeding"
label variable c122d    "Newborn recommendations:Importance of newborn vaccination"
label variable c122y    "Newborn recommendations:No newborn/post-partum recommendations given"
label variable c150     "Antenatal care card seen"
label variable c151     "Tetanus toxoid notation in antenatal care card"
label variable c152     "Weeks pregnant according to card"
label variable c154     "First pregnancy according to respondent"
label variable c155a    "Number of visits to this facility for this pregnancy"
label variable c156     "Given iron tablets, folic acid, combined tablet or prescriptions"
label variable c158     "Provider explained how to take tablets"
label variable c159     "Provider discussed side effects of iron tablets"
label variable c160a    "Iron side effect known by client:Nausea"
label variable c160b    "Iron side effect known by client:Black stools"
label variable c160c    "Iron side effect known by client:Constipation"
label variable c160x    "Iron side effect known by client:Other"
label variable c160z    "Iron side effect known by client:Don't know"
label variable c161     "Provider given or prescribed anti-malarial"
label variable c166     "Provider has discussed preparation for delivery"
label variable c166a    "Provider has discussed preparation for delivery (this/previous visit)"
label variable c167a    "Preparation for delivery:Emergency transport"
label variable c167b    "Preparation for delivery:Money"
label variable c167c    "Preparation for delivery:Disinfectant"
label variable c167d    "Preparation for delivery:Sterile blade/scissors to cut cord"
label variable c167e    "NA - Preparation for delivery:Gloves"
label variable c167f    "NA - Preparation for delivery:Cord tie/ clean string"
label variable c167x    "Preparation for delivery:Other"
label variable c167z    "Preparation for delivery:Don't know"
label variable c168     "Has enough money for delivery"
label variable c169     "Provider talked about pregnancy dangers/problems"
label variable c170a    "Client knows danger sign:Bleeding"
label variable c170b    "Client knows danger sign:Fever"
label variable c170c    "Client knows danger sign:Swollen hand, face or extremities"
label variable c170d    "Client knows danger sign:Tiredness or breathlessness"
label variable c170e    "Client knows danger sign:Headache or blurred vision"
label variable c170f    "Client knows danger sign:Convulsions"
label variable c170g    "Client knows danger sign:Reduced or absence of fetal movement"
label variable c170h    "Client knows danger sign:Premature rupture of membranes"
label variable c170i    "Client knows danger sign:Cough or difficulty breathing for 3 weeks or longer"
label variable c170x    "Client knows danger sign:Other"
label variable c170z    "Client knows danger sign:Don't know"
label variable c171a    "Provider advice if danger sign:Seek care at facility"
label variable c171b    "Provider advice if danger sign:Decrease activity"
label variable c171c    "Provider advice if danger sign:Change diet"
label variable c171x    "Provider advice if danger sign:Other"
label variable c171y    "Provider advice if danger sign:None"
label variable c172a    "Danger sign after delivery known:Heavy bleeding"
label variable c172b    "Danger sign after delivery known:Fever"
label variable c172c    "Danger sign after delivery known:Genital injuries"
label variable c172d    "Danger sign after delivery known:None thereof"
label variable c172y    "Danger sign after delivery known:None"
label variable c173     "Provider talked about diet during pregnancy"
label variable c174     "Provider discussed importance of exclusive breastfeeding"
label variable c175     "Number of months provider recommended for exclusive breastfeeding"
label variable c176     "Provider discussed place of delivery"
label variable c177     "Planned place of delivery"
label variable c178     "Provider discussed FP use after delivery"
label variable c179     "NA - Number of doses of IPT indicated on ANC card"
label variable c180     "Provider gave anti-malaria pills to client"
label variable c181     "Asked to swallow malaria pills in presence of provider"
label variable c182     "Provider advised use of ITN"
label variable c183     "Provider offered an ITN to client"
label variable c184     "Provider offered to sell client an ITN"
label variable sxa118   "Provider talked about danger signs in pregnancy"

#delimit ;
label define C001    
     1 "West"
     2 "Southeast"
     3 "North"
     4 "Northeast"
     5 "Artibonite"
     6 "Central"
     7 "South"
     8 "Grand-Anse"
     9 "Northwest"
    10 "Nippes"
;
label define C003    
     1 "Urban"
     2 "Rural"
;
label define C007    
     1 "University hospital"
     2 "Regional hospital"
     3 "Community referral hospital"
     4 "Hospital"
     5 "Health center with LIT"
     6 "Health center without LIT"
     7 "Dispensary"
;
label define C008    
     1 "Government/public"
     2 "NGO/ Private not for profit"
     3 "Private for profit"
     4 "Mission/ faith-based"
;
label define C020A   
     0 "Refused by provider or client"
     1 "Complete"
     7 "Not returned from field"
;
label define C020B   
     0 "Refused by client"
     1 "Complete"
     2 "Sick child admitted, not possible to continue"
     7 "Not returned from field"
;
label define C021    
     1 "ANC"
     2 "Child Sick"
     3 "Family Planning"
     6 "CS - Labor/Delivery"
;
label define C022    
     1 "Male"
     2 "Female"
;
label define C023    
     1 "Male"
     2 "Female"
;
label define C024    
     1 "Medical doctor (generalist)"
     2 "Surgeon (general)"
     3 "Medical specialist"
    21 "Nurse"
    22 "Nurse/midwife"
    23 "Auxiliary nurse"
    35 "Lab technician, medical technologist"
    71 "Auxiliary dentist"
    72 "Other community health workers"
    95 "Non-technical qualification"
    96 "Other"
;
label define C501    
     0 "Saw provider immediately"
   998 "Don't know"
;
label define C502A   
     0 "No problem"
     1 "Large problem"
     2 "Small problem"
     8 "Don't know"
;
label define C502B   
     0 "No problem"
     1 "Large problem"
     2 "Small problem"
     8 "Don't know"
;
label define C502C   
     0 "No problem"
     1 "Large problem"
     2 "Small problem"
     8 "Don't know"
;
label define C502E   
     0 "No problem"
     1 "Large problem"
     2 "Small problem"
     8 "Don't know"
;
label define C502F   
     0 "No problem"
     1 "Large problem"
     2 "Small problem"
     8 "Don't know"
;
label define C502G   
     0 "No problem"
     1 "Large problem"
     2 "Small problem"
     8 "Don't know"
;
label define C502H   
     0 "No problem"
     1 "Large problem"
     2 "Small problem"
     8 "Don't know"
;
label define C502I   
     0 "No problem"
     1 "Large problem"
     2 "Small problem"
     8 "Don't know"
;
label define C502J   
     0 "No problem"
     1 "Large problem"
     2 "Small problem"
     8 "Don't know"
;
label define C502K   
     0 "No problem"
     1 "Large problem"
     2 "Small problem"
     8 "Don't know"
;
label define C502L   
     0 "No problem"
     1 "Large problem"
     2 "Small problem"
     8 "Don't know"
;
label define C503    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define C504    
     0 "No"
     1 "Yes"
;
label define C505    
999998 "Don't know"
;
label define C507    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define C508    
     1 "Inconvenient operating hours"
     2 "Bad reputation"
     3 "Don't like personnel"
     4 "No medicine"
     5 "Prefers to remain anonymous"
     6 "More expensive"
     7 "Referral"
    96 "Other"
    98 "Don't know"
;
label define C510    
     1 "Mother"
     2 "Father"
     3 "Sibling"
     4 "Aunt or uncle"
     5 "Grandparent"
     6 "Other"
;
label define C511    
    98 "Don't know"
;
label define C512    
     0 "Never attended school"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
;
label define C514    
     0 "Cannot read or write"
     1 "Read only"
     2 "Read and write"
     8 "Don;t know"
;
label define C515    
     0 "No schooling"
     1 "Primary"
     2 "Post primary/technical"
     3 "Secondary"
     4 "Higher/University"
;
label define C517A   
  9797 "Inconsistent"
  9898 "Don't know"
;
label define C517B   
  9797 "Inconsistent"
  9898 "Don't know"
;
label define C518A   
  9797 "Inconsistent"
  9898 "Don't know"
;
label define C518B   
  9797 "Inconsistent"
  9898 "Don't know"
;
label define C520    
     1 "Very satisfied"
     2 "Somewhat satisfied"
     3 "Not satisfied"
;
label define C521    
     0 "No"
     1 "Yes"
     8 "DK"
;
label define C522    
     0 "No or incomplete observation"
     1 "Yes"
     2 "More than 1 reported as first"
;
label define SCDEPART
     0 "West Metropolitan"
     1 "Other west"
     2 "Southeast"
     3 "North"
     4 "Northeast"
     5 "Artibonite"
     6 "Central"
     7 "South"
     8 "Grand-Anse"
     9 "Northwest"
    10 "Nippes"
;
label define SCLOCAL 
     1 "Metropolitan"
     2 "Other urban"
     3 "Rural"
;
label define C101A   
     5 "5 or more visits"
     8 "Don't  know"
;
label define C101F   
     0 "One first visit, other not first visit"
     1 "Both the same"
     2 "Both greater than 1st visit"
;
label define C102    
     0 "No"
     1 "Yes, first"
     8 "Don't know"
;
label define C102F   
     1 "Both the same"
     2 "First pregnancy in observation, not first pregnancy reported by client"
     3 "First pregnancy reported by client, not first pregnancy in observation"
     8 "Observation responses is DK/Missing"
;
label define C103A   
     0 "No"
     1 "Yes"
;
label define C103B   
     0 "No"
     1 "Yes"
;
label define C103C   
     0 "No"
     1 "Yes"
;
label define C103D   
     0 "No"
     1 "Yes"
;
label define C103Y   
     0 "No"
     1 "Yes, none"
;
label define C104A   
     0 "No"
     1 "Yes"
;
label define C104B   
     0 "No"
     1 "Yes"
;
label define C104C   
     0 "No"
     1 "Yes"
;
label define C104D   
     0 "No"
     1 "Yes"
;
label define C104E   
     0 "No"
     1 "Yes"
;
label define C104F   
     0 "No"
     1 "Yes"
;
label define C104G   
     0 "No"
     1 "Yes"
;
label define C104H   
     0 "No"
     1 "Yes"
;
label define C104I   
     0 "No"
     1 "Yes"
;
label define C104J   
     0 "No"
     1 "Yes"
;
label define C104K   
     0 "No"
     1 "Yes"
;
label define C104Y   
     0 "No"
     1 "Yes, none"
;
label define C105A   
     0 "No"
     1 "Yes"
;
label define C105B   
     0 "No"
     1 "Yes"
;
label define C105C   
     0 "No"
     1 "Yes"
;
label define C105D   
     0 "No"
     1 "Yes"
;
label define C105E   
     0 "No"
     1 "Yes"
;
label define C105F   
     0 "No"
     1 "Yes"
;
label define C105G   
     0 "No"
     1 "Yes"
;
label define C105H   
     0 "No"
     1 "Yes"
;
label define C105X   
     0 "No"
     1 "Yes"
;
label define C105Y   
     0 "No"
     1 "Yes, none"
;
label define C105A1  
     0 "No"
     1 "Yes"
;
label define C105B1  
     0 "No"
     1 "Yes"
;
label define C105C1  
     0 "No"
     1 "Yes"
;
label define C105D1  
     0 "No"
     1 "Yes"
;
label define C105E1  
     0 "No"
     1 "Yes"
;
label define C105F1  
     0 "No"
     1 "Yes"
;
label define C105G1  
     0 "No"
     1 "Yes"
;
label define C105H1  
     0 "No"
     1 "Yes"
;
label define C105X1  
     0 "No"
     1 "Yes"
;
label define C105Y1  
     0 "No"
     1 "Yes, none"
;
label define C106A   
     0 "No"
     1 "Yes"
;
label define C106B   
     0 "No"
     1 "Yes"
;
label define C106C   
     0 "No"
     1 "Yes"
;
label define C106D   
     0 "No"
     1 "Yes"
;
label define C106K   
     0 "No"
     1 "Yes"
;
label define C106L   
     0 "No"
     1 "Yes"
;
label define C106M   
     0 "No"
     1 "Yes"
;
label define C106N   
     0 "No"
     1 "Yes"
;
label define C106O   
     0 "No"
     1 "Yes"
;
label define C106P   
     0 "No"
     1 "Yes"
;
label define C106Q   
     0 "No"
     1 "Yes"
;
label define C106R   
     0 "No"
     1 "Yes"
;
label define C106Y   
     0 "No"
     1 "Yes, none"
;
label define CF106A  
     0 "Activity not routinely done"
     1 "Observed"
     2 "Reported, not seen"
     8 "Don't know"
;
label define CF106K  
     0 "Activity not routinely done"
     1 "Observed"
     2 "Reported, not seen"
     8 "Don't know"
;
label define CF106XA 
     0 "Activity not routinely done"
     1 "Observed"
     2 "Reported, not seen"
     8 "Don't know"
;
label define CF106XB 
     0 "Activity not routinely done"
     1 "Observed"
     2 "Reported, not seen"
     8 "Don't know"
;
label define CF106XC 
     0 "Activity not routinely done"
     1 "Observed"
     2 "Reported, not seen"
     8 "Don't know"
;
label define CF106XD 
     0 "Activity not routinely done"
     1 "Observed"
     2 "Reported, not seen"
     8 "Don't know"
;
label define CF106XE 
     0 "Activity not routinely done"
     1 "Observed"
     2 "Reported, not seen"
     8 "Don't know"
;
label define CF106XF 
     0 "Activity not routinely done"
     1 "Observed"
     2 "Reported, not seen"
     8 "Don't know"
;
label define CF106XG 
     0 "Activity not routinely done"
     1 "Observed"
     2 "Reported, not seen"
     8 "Don't know"
;
label define C107A   
     0 "No"
     1 "Yes"
;
label define C107B   
     0 "No"
     1 "Yes"
;
label define C107C   
     0 "No"
     1 "Yes"
;
label define C107D   
     0 "No"
     1 "Yes"
;
label define C107E   
     0 "No"
     1 "Yes"
;
label define C107F   
     0 "No"
     1 "Yes"
;
label define C107P   
     0 "No"
     1 "Yes"
;
label define C107Q   
     0 "No"
     1 "Yes"
;
label define C107Y1  
     0 "No"
     1 "Yes, no iron prophylaxis"
;
label define C107Y2  
     0 "No"
     1 "Yes, no tetanus toxoid"
;
label define C107Y3  
     0 "No"
     1 "Yes, no deworming"
;
label define C108    
     0 "No"
     1 "Yes"
;
label define C110    
     0 "No"
     1 "Yes"
;
label define C111    
     0 "No"
     1 "Yes"
;
label define C111A   
     0 "No"
     1 "Yes"
;
label define C111B   
     0 "No"
     1 "Yes"
;
label define C111C   
     0 "No"
     1 "Yes"
;
label define C111E   
     0 "No"
     1 "Yes"
;
label define C113    
     0 "No"
     1 "Yes"
;
label define C114    
     0 "No"
     1 "Yes"
;
label define C115    
     0 "No"
     1 "Yes"
;
label define C116A   
     0 "No"
     1 "Yes"
     2 "No health card used"
;
label define C116    
     0 "No"
     1 "Yes"
     2 "No health card used"
     8 "Don't know"
;
label define C117    
    98 "Don't know"
;
label define C117F   
     0 "Inconsistent by more than 2 weeks"
     1 "Same number of weeks"
     2 "Consistent within 2 weeks"
;
label define C118    
     1 "Client sent home"
     2 "Client referred to lab or provider at same facility"
     3 "Client admitted to same facility"
     4 "Client referred to other facility"
;
label define C119A   
     0 "No"
     1 "Asked and performed"
     2 "Performed only"
     3 "Asked and referred"
     4 "Referred only"
     5 "Asked only"
;
label define C119B   
     0 "No"
     1 "Asked and performed"
     2 "Performed only"
     3 "Asked and referred"
     4 "Referred only"
     5 "Asked only"
;
label define C119C   
     0 "No"
     1 "Asked and performed"
     2 "Performed only"
     3 "Asked and referred"
     4 "Referred only"
     5 "Asked only"
;
label define C119D   
     0 "No"
     1 "Asked and performed"
     2 "Performed only"
     3 "Asked and referred"
     4 "Referred only"
     5 "Asked only"
;
label define C119Y   
     0 "No, did ask, refer or perform"
     1 "Yes, did not ask, refer, perform"
;
label define C120A   
     0 "No"
     1 "Yes"
;
label define C120B   
     0 "No"
     1 "Yes"
;
label define C120C   
     0 "No"
     1 "Yes"
;
label define C120D   
     0 "No"
     1 "Yes"
;
label define C120E   
     0 "No"
     1 "Yes"
;
label define C120Y   
     0 "No"
     1 "Yes, none"
;
label define C121A   
     0 "No"
     1 "Yes"
;
label define C121B   
     0 "No"
     1 "Yes"
;
label define C121C   
     0 "No"
     1 "Yes"
;
label define C121D   
     0 "No"
     1 "Yes"
;
label define C121E   
     0 "No"
     1 "Yes"
;
label define C121F   
     0 "No"
     1 "Yes"
;
label define C121G   
     0 "No"
     1 "Yes"
;
label define C121H   
     0 "No"
     1 "Yes"
;
label define C121I   
     0 "No"
     1 "Yes"
;
label define C121Y   
     0 "No"
     1 "Yes, none"
;
label define C122A   
     0 "No"
     1 "Yes"
;
label define C122B   
     0 "No"
     1 "Yes"
;
label define C122C   
     0 "No"
     1 "Yes"
;
label define C122D   
     0 "No"
     1 "Yes"
;
label define C122Y   
     0 "No"
     1 "Yes, no newborn/postpartum recommendations given"
;
label define C150    
     0 "No card/book used"
     1 "Yes, card seen"
     2 "Yes, card kept with facility"
;
label define C151    
     0 "No record"
     1 "Yes, 1 time"
     2 "Yes, 2 times"
     3 "Yes, 3 or more times"
     8 "Don't know"
;
label define C152    
    95 "No card available"
;
label define C154    
     0 "No"
     1 "Yes"
;
label define C155A   
     5 "More than 4 visits"
;
label define C156    
     0 "No"
     1 "Yes, this and previous visit"
     2 "Yes, only this visit"
     3 "Yes, only previous visit"
     8 "Don't know"
;
label define C158    
     0 "No"
     1 "Yes, this and previous visit"
     2 "Yes, only this visit"
     3 "Yes, only previous visit"
     8 "Don't know"
;
label define C159    
     0 "No"
     1 "Yes, this and previous visit"
     2 "Yes, only this visit"
     3 "Yes, only previous visit"
     8 "Don't know"
;
label define C160A   
     0 "No"
     1 "Yes"
;
label define C160B   
     0 "No"
     1 "Yes"
;
label define C160C   
     0 "No"
     1 "Yes"
;
label define C160X   
     0 "No"
     1 "Yes"
;
label define C160Z   
     0 "No"
     1 "Yes"
;
label define C161    
     0 "No"
     1 "Yes, this and previous visit"
     2 "Yes, only this visit"
     3 "Yes, only previous visit"
     8 "Don't know"
;
label define C166    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define C166A   
     0 "No"
     1 "Yes, this and previous visit"
     2 "Yes, only this visit"
     3 "Yes, only previous visit"
     8 "Don't know"
;
label define C167A   
     0 "No"
     1 "Yes"
;
label define C167B   
     0 "No"
     1 "Yes"
;
label define C167C   
     0 "No"
     1 "Yes"
;
label define C167D   
     0 "No"
     1 "Yes"
;
label define C167E   
     0 "No"
     1 "Yes"
;
label define C167F   
     0 "No"
     1 "Yes"
;
label define C167X   
     0 "No"
     1 "Yes"
;
label define C167Z   
     0 "No"
     1 "Yes"
;
label define C168    
     0 "No"
     1 "Yes, enough"
     2 "Yes, but not enough"
;
label define C169    
     0 "No"
     1 "Yes, this and previous visit"
     2 "Yes, only this visit"
     3 "Yes, only previous visit"
     8 "Don't know"
;
label define C170A   
     0 "No"
     1 "Yes"
;
label define C170B   
     0 "No"
     1 "Yes"
;
label define C170C   
     0 "No"
     1 "Yes"
;
label define C170D   
     0 "No"
     1 "Yes"
;
label define C170E   
     0 "No"
     1 "Yes"
;
label define C170F   
     0 "No"
     1 "Yes"
;
label define C170G   
     0 "No"
     1 "Yes"
;
label define C170H   
     0 "No"
     1 "Yes"
;
label define C170I   
     0 "No"
     1 "Yes"
;
label define C170X   
     0 "No"
     1 "Yes"
;
label define C170Z   
     0 "No"
     1 "Yes"
;
label define C171A   
     0 "No"
     1 "Yes"
;
label define C171B   
     0 "No"
     1 "Yes"
;
label define C171C   
     0 "No"
     1 "Yes"
;
label define C171X   
     0 "No"
     1 "Yes"
;
label define C171Y   
     0 "No"
     1 "Yes"
;
label define C172A   
     0 "No"
     1 "Yes"
;
label define C172B   
     0 "No"
     1 "Yes"
;
label define C172C   
     0 "No"
     1 "Yes"
;
label define C172D   
     0 "No"
     1 "Yes"
;
label define C172Y   
     0 "No"
     1 "Yes"
;
label define C173    
     0 "No"
     1 "Yes, this and previous visit"
     2 "Yes, only this visit"
     3 "Yes, only previous visit"
     8 "Don't know"
;
label define C174    
     0 "No"
     1 "Yes, this and previous visit"
     2 "Yes, only this visit"
     3 "Yes, only previous visit"
     8 "Don't know"
;
label define C175    
     4 "4-6 months"
     6 "6 months"
    96 "Other"
    98 "Don't know"
;
label define C176    
     0 "No"
     1 "Yes, this and previous visit"
     2 "Yes, only this visit"
     3 "Yes, only previous visit"
     8 "Don't know"
;
label define C177    
     1 "This facility"
     2 "At other health facility"
     3 "At home"
     4 "At TBA home"
     6 "Other location"
     8 "Don't know/not decided"
;
label define C178    
     0 "No"
     1 "Yes, this and previous visit"
     2 "Yes, only this visit"
     3 "Yes, only previous visit"
     8 "Don't know"
;
label define C179    
     0 "No indication of doses"
;
label define C180    
     0 "No"
     1 "Yes, see C161 for timing of provision"
     8 "Don't know"
;
label define C181    
     0 "No"
     1 "Yes"
;
label define C182    
     0 "No"
     1 "Yes, this and previous visit"
     2 "Yes, only this visit"
     3 "Yes, only previous visit"
     8 "Don't know"
;
label define C183    
     0 "No"
     1 "Yes, this and previous visit"
     2 "Yes, only this visit"
     3 "Yes, only previous visit"
     8 "Don't know"
;
label define C184    
     0 "No"
     1 "Yes, this and previous visit"
     2 "Yes, only this visit"
     3 "Yes, only previous visit"
     8 "Don't know"
;
label define SXA118  
     0 "No"
     1 "Yes, this and previous visit"
     2 "Yes, this visit only"
     3 "Yes, previous visit only"
     8 "Don't know"
;

#delimit cr
label values c001     C001    
label values c003     C003    
label values c007     C007    
label values c008     C008    
label values c020a    C020A   
label values c020b    C020B   
label values c021     C021    
label values c022     C022    
label values c023     C023    
label values c024     C024    
label values c501     C501    
label values c502a    C502A   
label values c502b    C502B   
label values c502c    C502C   
label values c502e    C502E   
label values c502f    C502F   
label values c502g    C502G   
label values c502h    C502H   
label values c502i    C502I   
label values c502j    C502J   
label values c502k    C502K   
label values c502l    C502L   
label values c503     C503    
label values c504     C504    
label values c505     C505    
label values c507     C507    
label values c508     C508    
label values c510     C510    
label values c511     C511    
label values c512     C512    
label values c514     C514    
label values c515     C515    
label values c517a    C517A   
label values c517b    C517B   
label values c518a    C518A   
label values c518b    C518B   
label values c520     C520    
label values c521     C521    
label values c522     C522    
label values scdepart SCDEPART
label values sclocal  SCLOCAL 
label values c101a    C101A   
label values c101f    C101F   
label values c102     C102    
label values c102f    C102F   
label values c103a    C103A   
label values c103b    C103B   
label values c103c    C103C   
label values c103d    C103D   
label values c103y    C103Y   
label values c104a    C104A   
label values c104b    C104B   
label values c104c    C104C   
label values c104d    C104D   
label values c104e    C104E   
label values c104f    C104F   
label values c104g    C104G   
label values c104h    C104H   
label values c104i    C104I   
label values c104j    C104J   
label values c104k    C104K   
label values c104y    C104Y   
label values c105a    C105A   
label values c105b    C105B   
label values c105c    C105C   
label values c105d    C105D   
label values c105e    C105E   
label values c105f    C105F   
label values c105g    C105G   
label values c105h    C105H   
label values c105x    C105X   
label values c105y    C105Y   
label values c105a1   C105A1  
label values c105b1   C105B1  
label values c105c1   C105C1  
label values c105d1   C105D1  
label values c105e1   C105E1  
label values c105f1   C105F1  
label values c105g1   C105G1  
label values c105h1   C105H1  
label values c105x1   C105X1  
label values c105y1   C105Y1  
label values c106a    C106A   
label values c106b    C106B   
label values c106c    C106C   
label values c106d    C106D   
label values c106k    C106K   
label values c106l    C106L   
label values c106m    C106M   
label values c106n    C106N   
label values c106o    C106O   
label values c106p    C106P   
label values c106q    C106Q   
label values c106r    C106R   
label values c106y    C106Y   
label values cf106a   CF106A  
label values cf106k   CF106K  
label values cf106xa  CF106XA 
label values cf106xb  CF106XB 
label values cf106xc  CF106XC 
label values cf106xd  CF106XD 
label values cf106xe  CF106XE 
label values cf106xf  CF106XF 
label values cf106xg  CF106XG 
label values c107a    C107A   
label values c107b    C107B   
label values c107c    C107C   
label values c107d    C107D   
label values c107e    C107E   
label values c107f    C107F   
label values c107p    C107P   
label values c107q    C107Q   
label values c107y1   C107Y1  
label values c107y2   C107Y2  
label values c107y3   C107Y3  
label values c108     C108    
label values c110     C110    
label values c111     C111    
label values c111a    C111A   
label values c111b    C111B   
label values c111c    C111C   
label values c111e    C111E   
label values c113     C113    
label values c114     C114    
label values c115     C115    
label values c116a    C116A   
label values c116     C116    
label values c117     C117    
label values c117f    C117F   
label values c118     C118    
label values c119a    C119A   
label values c119b    C119B   
label values c119c    C119C   
label values c119d    C119D   
label values c119y    C119Y   
label values c120a    C120A   
label values c120b    C120B   
label values c120c    C120C   
label values c120d    C120D   
label values c120e    C120E   
label values c120y    C120Y   
label values c121a    C121A   
label values c121b    C121B   
label values c121c    C121C   
label values c121d    C121D   
label values c121e    C121E   
label values c121f    C121F   
label values c121g    C121G   
label values c121h    C121H   
label values c121i    C121I   
label values c121y    C121Y   
label values c122a    C122A   
label values c122b    C122B   
label values c122c    C122C   
label values c122d    C122D   
label values c122y    C122Y   
label values c150     C150    
label values c151     C151    
label values c152     C152    
label values c154     C154    
label values c155a    C155A   
label values c156     C156    
label values c158     C158    
label values c159     C159    
label values c160a    C160A   
label values c160b    C160B   
label values c160c    C160C   
label values c160x    C160X   
label values c160z    C160Z   
label values c161     C161    
label values c166     C166    
label values c166a    C166A   
label values c167a    C167A   
label values c167b    C167B   
label values c167c    C167C   
label values c167d    C167D   
label values c167e    C167E   
label values c167f    C167F   
label values c167x    C167X   
label values c167z    C167Z   
label values c168     C168    
label values c169     C169    
label values c170a    C170A   
label values c170b    C170B   
label values c170c    C170C   
label values c170d    C170D   
label values c170e    C170E   
label values c170f    C170F   
label values c170g    C170G   
label values c170h    C170H   
label values c170i    C170I   
label values c170x    C170X   
label values c170z    C170Z   
label values c171a    C171A   
label values c171b    C171B   
label values c171c    C171C   
label values c171x    C171X   
label values c171y    C171Y   
label values c172a    C172A   
label values c172b    C172B   
label values c172c    C172C   
label values c172d    C172D   
label values c172y    C172Y   
label values c173     C173    
label values c174     C174    
label values c175     C175    
label values c176     C176    
label values c177     C177    
label values c178     C178    
label values c179     C179    
label values c180     C180    
label values c181     C181    
label values c182     C182    
label values c183     C183    
label values c184     C184    
label values sxa118   SXA118  
