infix using "C:\HAITISPA_FIN\ARCHIVE\HTPV6BFLSP.dct"

label variable facil    "Facility identification"
label variable provno   "Provider serial number"
label variable pintv    "Interviewer code"
label variable psex     "Provider sex"
label variable pstatus  "Provider status"
label variable ancobs   "ANC observations"
label variable fpobs    "FP observations"
label variable scobs    "Sick child observations"
label variable stiobs   "STI observations"
label variable prevint  "Previously interviewed at another facility"
label variable ppfacil  "Previous facility number"
label variable pday     "Day of interview"
label variable pmonth   "Month of interview"
label variable pyear    "Year of interview"
label variable p101     "Agree to interview"
label variable pstarth  "Start of interview (hour)"
label variable pstartm  "Start of interview (minutes)"
label variable anyserv  "Any service"
label variable provwt   "provider weight"
label variable p102     "Total years of education"
label variable p103     "Qualification"
label variable p104     "Year of graduation"
label variable p105     "Year started working in facility"
label variable p106     "Doses of HepB"
label variable p107     "Receive any vaccination"
label variable p108     "Manager/in-charge"
label variable p200_1   "Past 3 years general training"
label variable p200_2   "Past 3 years general training"
label variable p200_3   "Past 3 years general training"
label variable p200_4   "Past 3 years general training"
label variable p202     "Youth-friendly services"
label variable p203     "Received training in YFS past 3 years"
label variable p204     "Diagnose or treat malaria"
label variable p205     "Received training malaria past 3 years"
label variable p206_1   "Malaria training"
label variable p206_2   "Malaria training"
label variable p206_3   "Malaria training"
label variable p206_4   "Malaria training"
label variable p206_5   "Malaria training"
label variable p206_6   "Malaria training"
label variable p207     "Diagnose or manage diabetes"
label variable p208     "Training diabetes past 3 years"
label variable p209     "Diagnose or manage cardiovascular disease"
label variable p210     "Training cardiovascular disease past 3 years"
label variable p211     "Diagnose or manage chronic respiratory diseases"
label variable p212     "Training on chronic respiratory diseases in past 3 years"
label variable p300     "Provide child immunization services"
label variable p301     "Provide child growth monitoring services"
label variable p302     "Provide child curative care services"
label variable p303     "Training past 3 years child health/illnesses"
label variable p304_01  "Specific child health training"
label variable p304_02  "Specific child health training"
label variable p304_03  "Specific child health training"
label variable p304_04  "Specific child health training"
label variable p304_05  "Specific child health training"
label variable p304_06  "Specific child health training"
label variable p304_07  "Specific child health training"
label variable p304_08  "Specific child health training"
label variable p304_09  "Specific child health training"
label variable p304_10  "Specific child health training"
label variable p304_11  "Specific child health training"
label variable p304_12  "Specific child health training"
label variable p304_13  "Specific child health training"
label variable p400     "Provide FP services"
label variable p401     "Training past 3 years FP"
label variable p403_1   "Specific FP training"
label variable p403_2   "Specific FP training"
label variable p403_3   "Specific FP training"
label variable p403_4   "Specific FP training"
label variable p403_5   "Specific FP training"
label variable p403_6   "Specific FP training"
label variable p403_7   "Specific FP training"
label variable p403_8   "Specific FP training"
label variable p500     "Provide ANC/PNC care"
label variable p501     "Training ANC/PNC"
label variable p502_1   "Specific ANC/PNC training"
label variable p502_2   "Specific ANC/PNC training"
label variable p502_3   "Specific ANC/PNC training"
label variable p502_4   "Specific ANC/PNC training"
label variable p503     "Provide PMTCT services"
label variable p504     "Training PMTCT/newborn health and HIV past 3 years"
label variable p505_1   "Specific PMTCT training"
label variable p505_2   "Specific PMTCT training"
label variable p505_3   "Specific PMTCT training"
label variable p505_4   "Specific PMTCT training"
label variable p505_5   "Specific PMTCT training"
label variable p506     "Provide delivery services"
label variable p507     "Total delilveries past 6 months"
label variable p508     "Use of partograph"
label variable p509     "Training related to delivery care past 3 years"
label variable p510_1   "Specific delivery care training"
label variable p510_2   "Specific delivery care training"
label variable p510_3   "Specific delivery care training"
label variable p510_4   "Specific delivery care training"
label variable p510_5   "Specific delivery care training"
label variable p510_6   "Specific delivery care training"
label variable p510_7   "Specific delivery care training"
label variable p511     "Provide newborn care"
label variable p512     "Training in newborn care in past 3 years"
label variable p513_1   "Specific newborn training"
label variable p513_2   "Specific newborn training"
label variable p513_3   "Specific newborn training"
label variable p513_4   "Specific newborn training"
label variable p513_5   "Specific newborn training"
label variable p513_6   "Specific newborn training"
label variable p600     "Provide STI services"
label variable p601     "Training in STIs past 3 years"
label variable p602_1   "Specific STI training"
label variable p602_2   "Specific STI training"
label variable p602_3   "Specific STI training"
label variable p603a_1  "Provide specific TB service"
label variable p603a_2  "Provide specific TB service"
label variable p603a_3  "Provide specific TB service"
label variable p603a_4  "Provide specific TB service"
label variable p603a_5  "Provide specific TB service"
label variable p603a_6  "Provide specific TB service"
label variable p603a_7  "Provide specific TB service"
label variable p603b_1  "Training in specific TB service past 3 years"
label variable p603b_2  "Training in specific TB service past 3 years"
label variable p603b_3  "Training in specific TB service past 3 years"
label variable p603b_4  "Training in specific TB service past 3 years"
label variable p603b_5  "Training in specific TB service past 3 years"
label variable p603b_6  "Training in specific TB service past 3 years"
label variable p603b_7  "Training in specific TB service past 3 years"
label variable p604a_1  "Provide specific HIV service"
label variable p604a_2  "Provide specific HIV service"
label variable p604a_3  "Provide specific HIV service"
label variable p604a_4  "Provide specific HIV service"
label variable p604a_5  "Provide specific HIV service"
label variable p604a_6  "Provide specific HIV service"
label variable p604a_7  "Provide specific HIV service"
label variable p604a_8  "Provide specific HIV service"
label variable p604a_9  "Provide specific HIV service"
label variable p604b_1  "Training in specific HIV service past 3 years"
label variable p604b_2  "Training in specific HIV service past 3 years"
label variable p604b_3  "Training in specific HIV service past 3 years"
label variable p604b_4  "Training in specific HIV service past 3 years"
label variable p604b_5  "Training in specific HIV service past 3 years"
label variable p604b_6  "Training in specific HIV service past 3 years"
label variable p604b_7  "Training in specific HIV service past 3 years"
label variable p604b_8  "Training in specific HIV service past 3 years"
label variable p604b_9  "Training in specific HIV service past 3 years"
label variable p700     "Conduct lab tests"
label variable p701_1   "Specific lab tests"
label variable p701_2   "Specific lab tests"
label variable p701_3   "Specific lab tests"
label variable p701_4   "Specific lab tests"
label variable p701_5   "Specific lab tests"
label variable p701_6   "Specific lab tests"
label variable p702     "Training in past 3 years in lab work"
label variable p703_1   "Specific training in lab work"
label variable p703_2   "Specific training in lab work"
label variable p703_3   "Specific training in lab work"
label variable p703_4   "Specific training in lab work"
label variable p703_5   "Specific training in lab work"
label variable p703_6   "Specific training in lab work"
label variable p703_7   "Specific training in lab work"
label variable p800     "Average hours worked each week"
label variable p801     "Recent supervision"
label variable p802     "Times supervised in past 6 months"
label variable p803_1   "Specific supervision experienced"
label variable p803_2   "Specific supervision experienced"
label variable p803_3   "Specific supervision experienced"
label variable p803_4   "Specific supervision experienced"
label variable p803_5   "Specific supervision experienced"
label variable p803_6   "Specific supervision experienced"
label variable p804     "Written job description"
label variable p805     "Opportunities for promotion"
label variable p806     "Salary supplement received"
label variable p807     "Non-mnoetary incentives received"
label variable p808_1   "Rated improvements desired"
label variable p808_2   "Rated improvements desired"
label variable p808_3   "Rated improvements desired"
label variable pfinh    "Fin de l'interview: heure"
label variable pfinm    "Fin de l'interview: minute"

#delimit ;
label define PINTV
     1 "Paul Brea"
     2 "Claudia Marchena"
     3 "Keith Purvis"
     4 "Albert Themme"
    10 "Team 1 superviseur 10"
    11 "Team 1 interviewer 11"
    12 "Team 1 interviewer 12"
    13 "Team 1 interviewer 13"
    14 "Team 1 interviewer 14"
    15 "Team 2 superviseur 15"
    16 "Team 2 interviewer 16"
    17 "Team 2 interviewer 17"
    18 "Team 2 interviewer 18"
    19 "Team 2 interviewer 19"
    20 "Team 3 superviseur 20"
    21 "Team 3 interviewer 21"
    22 "Team 3 interviewer 22"
    23 "Team 3 interviewer 23"
    24 "Team 3 interviewer 24"
    25 "Team 4 supervisor 25"
    26 "Team 4 interviewer 26"
    27 "Team 4 interviewer 27"
    28 "Team 4 interviewer 28"
    29 "Team 4 interviewer 29"
    30 "Team 5 supervisor 30"
    31 "Team 5 interviewer 31"
    32 "Team 5 interviewer 32"
    33 "Team 5 interviewer 33"
    34 "Team 5 interviewer 34"
    35 "Team 6 supervisor 35"
    36 "Team 6 interviewer 36"
    37 "Team 6 interviewer 37"
    38 "Team 6 interviewer 38"
    39 "Team 6 interviewer 39"
    40 "Team 7 supervisor 40"
    41 "Team 7 interviewer 41"
    42 "Team 7 interviewer 42"
    43 "Team 7 interviewer 43"
    44 "Team 7 interviewer 44"
    45 "Team 8 supervisor 45"
    46 "Team 8 interviewer 46"
    47 "Team 8 interviewer 47"
    48 "Team 8 interviewer 48"
    49 "Team 8 interviewer 49"
    50 "Team 9 supervisor 50"
    51 "Team 9 interviewer 51"
    52 "Team 9 interviewer 52"
    53 "Team 9 interviewer 53"
    54 "Team 9 interviewer 54"
    55 "Team 10 supervisor 55"
    56 "Team 10 interviewer 56"
    57 "Team 10 interviewer 57"
    58 "Team 10 interviewer 58"
    59 "Team 10 interviewer 59"
    60 "Team 11 supervisor 60"
    61 "Team 11 interviewer 61"
    62 "Team 11 interviewer 62"
    63 "Team 11 interviewer 63"
    64 "Team 11 interviewer 64"
    65 "Team 12 supervisor 65"
    66 "Team 12 interviewer 66"
    67 "Team 12 interviewer 67"
    68 "Team 12 interviewer 68"
    69 "Team 12 interviewer 69"
    70 "Team 13 supervisor 70"
    71 "Team 13 interviewer 71"
    72 "Team 13 interviewer 72"
    73 "Team 13 interviewer 73"
    74 "Team 13 interviewer 74"
    75 "Team 14 supervisor 75"
    76 "Team 14 interviewer 76"
    77 "Team 14 interviewer 77"
    78 "Team 14 interviewer 78"
    79 "Team 14 interviewer 79"
    80 "Team 15 supervisor 80"
    81 "Team 13 interviewer 81"
    82 "Team 15 interviewer 82"
    83 "Team 15 interviewer 83"
    84 "Team 15 interviewer 84"
    85 "Team 16 supervisor 85"
    86 "Team 16 interviewer 86"
    87 "Team 16 interviewer 87"
    88 "Team 16 interviewer 88"
    89 "Team 16 interviewer 89"
;
label define PSEX
     1 "Male"
     2 "Female"
;
label define PSTATUS
     1 "Assigned"
     2 "Seconded"
;
label define PREVINT
     1 "Yes"
     2 "No"
;
label define P101
     1 "Yes"
     2 "No"
;
label define PSTARTH
    98 "Ne sait pas"
;
label define PSTARTM
    98 "Ne sait pas"
;
label define ANYSERV
     0 "No"
     1 "Yes"
;
label define P103
     1 "Medical doctor (generalist)"
     2 "Surgeon (general)"
     3 "Medical specialist"
     4 "Lab technician"
     5 "Radiology technician"
     6 "Medical imagery technician"
     7 "Nurse"
     8 "Nurse/midwife"
     9 "Auxiliary nurse"
    10 "Pharmacist"
    11 "Auxiliary pharmacist"
    12 "Dental lab technician"
    13 "Dental hygienist"
    14 "Auxiliary dentist"
    15 "Other community health workers"
    95 "Non-technical qualification"
    96 "Other"
;
label define P106
     1 "Yes, one dose"
     2 "Yes, 2 doses"
     3 "Yes 3 or more doses"
     4 "None"
     8 "DK"
;
label define P107
     1 "Yes"
     2 "No"
;
label define P108
     1 "Yes"
     2 "No"
;
label define P200
     1 "Yes, within past 24 months"
     2 "Yes over 24 months ago"
     3 "No, in-service training or updates"
;
label define P202
     1 "Yes"
     2 "No"
;
label define P203
     1 "Yes, within past 24 months"
     2 "Yes, over 24 months ago"
     3 "No training or updates"
;
label define P204
     1 "Yes"
     2 "No"
;
label define P205
     1 "Yes"
     2 "No"
;
label define P206
     1 "Yes, within past 24 months"
     2 "Yes, over 24 months ago"
     3 "No training or updates"
;
label define P207
     1 "Yes"
     2 "No"
;
label define P208
     1 "Yes, within past 24 months"
     2 "Yes, over 24 months ago"
     3 "No training or updates"
;
label define P209
     1 "Yes"
     2 "No"
;
label define P210
     1 "Yes, within past 24 months"
     2 "Yes, over 24 months ago"
     3 "No training or updates"
;
label define P211
     1 "Yes"
     2 "No"
;
label define P212
     1 "Yes, within past 24 months"
     2 "Yes, over 24 months ago"
     3 "No training or updates"
;
label define P300
     1 "Yes"
     2 "No"
;
label define P301
     1 "Yes"
     2 "No"
;
label define P302
     1 "Yes"
     2 "No"
;
label define P303
     1 "Yes"
     2 "No"
;
label define P304
     1 "Yes, within past 24 months"
     2 "Yes, over 24 months ago"
     3 "No training or updates"
;
label define P400
     1 "Yes"
     2 "No"
;
label define P401
     1 "Yes"
     2 "No"
;
label define P403
     1 "Yes, within past 24 months"
     2 "Yes, over 24 months ago"
     3 "No in-service training or updates"
;
label define P500
     1 "Yes, antenatal"
     2 "Yes, postnatal"
     3 "Yes, both"
     4 "No, neither"
;
label define P501
     1 "Yes"
     2 "No"
;
label define P502
     1 "Yes, within past 24 months"
     2 "Yes, over 24 months ago"
     3 "No in-service training or updates"
;
label define P504
     1 "Yes"
     2 "No"
;
label define P505
     1 "Yes, within past 24 months"
     2 "Yes, over 24 months ago"
     3 "No in-service training or updates"
;
label define P506
     1 "Yes"
     2 "No"
;
label define P508
     0 "Never"
     1 "Withnin past week"
     2 "Within past month"
     3 "Within past 6 months"
     4 "Over 6 months ago"
;
label define P509
     1 "Yes"
     2 "No"
;
label define P510
     1 "Yes, within past 24 months"
     2 "Yes, over 24 months ago"
     3 "No in-service training or updates"
;
label define P511
     1 "Yes"
     2 "No"
;
label define P512
     1 "Yes"
     2 "No"
;
label define P513
     1 "Yes, within past 24 months"
     2 "Yes, over 24 months ago"
     3 "No in-service training or updates"
;
label define P600
     1 "Yes"
     2 "No"
;
label define P601
     1 "Yes"
     2 "No"
;
label define P602
     1 "Yes, within past 24 months"
     2 "Yes, over 24 months ago"
     3 "No in-service training or updates"
;
label define P603A
     1 "Yes"
     2 "No"
;
label define P603B
     1 "Yes, within past 24 months"
     2 "Yes, over 24 months ago"
     3 "No training or updates"
;
label define P604A
     1 "Yes"
     2 "No"
;
label define P604B
     1 "Yes, within past 24 months"
     2 "Yes, over 24 months ago"
     3 "No training or updates"
;
label define P700
     1 "Yes"
     2 "No"
;
label define P701
     1 "Yes"
     2 "No"
;
label define P702
     1 "Yes"
     2 "No"
;
label define P703
     1 "Yes, within past 24 months"
     2 "Yes, over 24 months ago"
     3 "No training or updates"
;
label define P801
     1 "Yes, in past 3 months"
     2 "Yes, in past 4-6 months"
     3 "Yes, in past 7-12 months"
     4 "Yes, more than 12 months ago"
     5 "No"
;
label define P802
    96 "Every day"
;
label define P803
     1 "Yes"
     2 "No"
     8 "DK"
;
label define P804
     1 "Yes, observed"
     2 "Yes, reported, not seen"
     3 "No"
;
label define P805
     1 "Yes"
     2 "No"
     8 "DK"
;
label define PFINH
    98 "Ne sait pas"
;
label define PFINM
    98 "Ne  sait pas"
;

#delimit cr
label values pintv    PINTV
label values psex     PSEX
label values pstatus  PSTATUS
label values prevint  PREVINT
label values p101     P101
label values pstarth  PSTARTH
label values pstartm  PSTARTM
label values anyserv  ANYSERV
label values p103     P103
label values p106     P106
label values p107     P107
label values p108     P108
label values p200_1   P200
label values p200_2   P200
label values p200_3   P200
label values p200_4   P200
label values p202     P202
label values p203     P203
label values p204     P204
label values p205     P205
label values p206_1   P206
label values p206_2   P206
label values p206_3   P206
label values p206_4   P206
label values p206_5   P206
label values p206_6   P206
label values p207     P207
label values p208     P208
label values p209     P209
label values p210     P210
label values p211     P211
label values p212     P212
label values p300     P300
label values p301     P301
label values p302     P302
label values p303     P303
label values p304_01  P304
label values p304_02  P304
label values p304_03  P304
label values p304_04  P304
label values p304_05  P304
label values p304_06  P304
label values p304_07  P304
label values p304_08  P304
label values p304_09  P304
label values p304_10  P304
label values p304_11  P304
label values p304_12  P304
label values p304_13  P304
label values p400     P400
label values p401     P401
label values p403_1   P403
label values p403_2   P403
label values p403_3   P403
label values p403_4   P403
label values p403_5   P403
label values p403_6   P403
label values p403_7   P403
label values p403_8   P403
label values p500     P500
label values p501     P501
label values p502_1   P502
label values p502_2   P502
label values p502_3   P502
label values p502_4   P502
label values p504     P504
label values p505_1   P505
label values p505_2   P505
label values p505_3   P505
label values p505_4   P505
label values p505_5   P505
label values p506     P506
label values p508     P508
label values p509     P509
label values p510_1   P510
label values p510_2   P510
label values p510_3   P510
label values p510_4   P510
label values p510_5   P510
label values p510_6   P510
label values p510_7   P510
label values p511     P511
label values p512     P512
label values p513_1   P513
label values p513_2   P513
label values p513_3   P513
label values p513_4   P513
label values p513_5   P513
label values p513_6   P513
label values p600     P600
label values p601     P601
label values p602_1   P602
label values p602_2   P602
label values p602_3   P602
label values p603a_1  P603A
label values p603a_2  P603A
label values p603a_3  P603A
label values p603a_4  P603A
label values p603a_5  P603A
label values p603a_6  P603A
label values p603a_7  P603A
label values p603b_1  P603B
label values p603b_2  P603B
label values p603b_3  P603B
label values p603b_4  P603B
label values p603b_5  P603B
label values p603b_6  P603B
label values p603b_7  P603B
label values p604a_1  P604A
label values p604a_2  P604A
label values p604a_3  P604A
label values p604a_4  P604A
label values p604a_5  P604A
label values p604a_6  P604A
label values p604a_7  P604A
label values p604a_8  P604A
label values p604a_9  P604A
label values p604b_1  P604B
label values p604b_2  P604B
label values p604b_3  P604B
label values p604b_4  P604B
label values p604b_5  P604B
label values p604b_6  P604B
label values p604b_7  P604B
label values p604b_8  P604B
label values p604b_9  P604B
label values p700     P700
label values p701_1   P701
label values p701_2   P701
label values p701_3   P701
label values p701_4   P701
label values p701_5   P701
label values p701_6   P701
label values p702     P702
label values p703_1   P703
label values p703_2   P703
label values p703_3   P703
label values p703_4   P703
label values p703_5   P703
label values p703_6   P703
label values p703_7   P703
label values p801     P801
label values p802     P802
label values p803_1   P803
label values p803_2   P803
label values p803_3   P803
label values p803_4   P803
label values p803_5   P803
label values p803_6   P803
label values p804     P804
label values p805     P805
label values pfinh    PFINH
label values pfinm    PFINM
