infix using "C:\NEWSPA_AUG30\HT6A\EXPORT\EXPORTEDFILES\HTFP6AFLSR.dct"

label variable inv_id   "INVENTORY ID"
label variable p_id     "Unit/Provider line number ID"
label variable obs_n    "Client type code"
label variable obs_id   "Client ID"
label variable c000     "Survey phase"
label variable c001     "Region (Country-specific)"
label variable c002     "District (Country-specific)"
label variable c003     "Urban/rural"
label variable c004     "Facility number"
label variable c004p    "Provider line number"
label variable c004ct   "Client type code (alpha)"
label variable c004cn   "Client ID number"
label variable c005     "Sample weight"
label variable c007     "Facility type (Country-specific)"
label variable c008     "Operating Authority (Country-specific)"
label variable c009a    "Interviewer for observation"
label variable c009b    "Interviewer for exit interview"
label variable c009c    "NA - Keyer"
label variable c020a    "Result of observation"
label variable c020b    "Result of exit intervIew"
label variable c021     "Type of client"
label variable c022     "Sex of provider"
label variable c023     "Sex of client/sick child"
label variable c024     "Technical qualification of provider (Country-specific within ranges)"
label variable c032     "Month of observation/interview"
label variable c033     "Year of observation/interview"
label variable c033d    "Day of observation/interview"
label variable c501     "Duration of wait before being seen (in minutes)"
label variable c502a    "Client problem during visit:Time had to wait"
label variable c502b    "Client problem during visit:Ability to discuss problems/concerns"
label variable c502c    "Client problem during visit:Amount of explanation for problem/tx"
label variable c502e    "Client problem during visit:Visual privacy"
label variable c502f    "Client problem during visit:Auditory privacy"
label variable c502g    "Client problem during visit:Availability of medicines at facility"
label variable c502h    "Client problem during visit:Hours of service"
label variable c502i    "Client problem during visit:Days of service"
label variable c502j    "Client problem during visit:Cleanliness of facility"
label variable c502k    "Client problem during visit:Staff treatment of client"
label variable c502l    "Client problem during visit:Cost"
label variable c503     "Part of prepayment plan/insurance that pays part of cost"
label variable c504     "Charged for services today"
label variable c505     "Total amount paid (in gourdes)"
label variable c507     "Facility nearest to home"
label variable c508     "Reason did not go to nearest facility"
label variable c510     "Caretaker relationship to sick child (Sick child exit only)"
label variable c511     "Age of client (caretaker of client)"
label variable c512     "Highest level of education attended"
label variable c514     "Literacy level"
label variable c515     "Country reported highest level of education attended (CS)"
label variable c517a    "Time observation interview began"
label variable c517b    "Time observation interview ended"
label variable c518a    "Time exit interview began"
label variable c518b    "Time exit interview ended"
label variable c520     "Opinion of services given today"
label variable c521     "Would recommend to friend/family member"
label variable c522     "First observation for this provider for this service"
label variable scdepart "CS - Region with West separated for metropolitan and other"
label variable sclocal  "Metropoliltan/other urban/rural"
label variable c301a    "Previous contact with provider at this FP clinic"
label variable c301b    "Female client has ever been pregnant"
label variable c302a    "All client history provided: Age"
label variable c302b    "All client history provided: Number of living children"
label variable c302c    "Female client history provided: Last delivery date/age of youngest child"
label variable c302e    "Female client history  provided: Current pregnancy status"
label variable c302f    "All client history provided: Desire for a child or more children"
label variable c302g    "All client history provided: Desired timing for birth of next child"
label variable c302h    "Female client history provided: Breastfeeding status"
label variable c302i    "Female client history provided: Regularity of menstrual cycle"
label variable c302y1   "All client history provided: No history data collection observed"
label variable c302y2   "Female client history provided: No history data collection observed"
label variable c303a    "Physical exam/health question asked:Blood pressure"
label variable c303b    "Physical exam/health question asked:client weighed"
label variable c303c    "Physical exam/health question asked:Smoking status"
label variable c303d    "Physical exam/health question asked:STI symptoms"
label variable c303e    "Physical exam/health question asked:Chronic illnesses"
label variable c303f    "Physical exam/health question asked:Look at client's health card"
label variable c303g    "CS - Physical exam/health question asked:About medicines client is taking"
label variable c303y    "Physical exam/health question asked:No physical exam/ health questions asked"
label variable cf303a   "Routine action in facility: Blood pressure"
label variable cf303b   "Routine action in facility: Weigh client"
label variable cf303xa  "Routine action in facility: Conduct group health education"
label variable c304a    "Client privacy:Ensure visual privacy"
label variable c304b    "Client privacy:Ensure auditory privacy"
label variable c304c    "Client privacy:Assure client orally of confidentiality"
label variable c304y    "Client privacy:No privacy issues observed"
label variable c305a    "Issues discussed:Partner's attitude toward FP"
label variable c305b    "Issues discussed:Partner status(number, partner's number, partner absent)"
label variable c305c    "Issues discussed:Risk of STIs"
label variable c305d    "Issues discussed:Use of condoms to prevent STIs"
label variable c305e    "Issues discussed:Use condoms with other method to avoid pregnancy and STIs"
label variable c305f    "Issues discussed:Ask client about questions/concerns regarding current method(s)"
label variable c305g    "Issues discussed:Client expressed concerns or asked questions"
label variable c305y    "Issues discussed:Observed no issues discussed"
label variable c306a    "Method provided/ prescribed:Combined oral pill"
label variable c306b    "Method provided/ prescribed:Progesterone only pill"
label variable c306c    "Method provided/ prescribed:Oral pill type unknown"
label variable c306d    "Method provided/ prescribed:Injectable (1 month)"
label variable c306e    "Method provided/ prescribed:Injectable (2-3 months)"
label variable c306f    "NA - Method provided/ prescribed:Injectable type unknown"
label variable c306g    "Method provided/ prescribed:Implant"
label variable c306h    "NA - Method provided/ prescribed:Implant 2nd type"
label variable c306i    "Method provided/ prescribed:Male condom"
label variable c306j    "Method provided/ prescribed:Female condom"
label variable c306k    "Method provided/ prescribed:IUCD"
label variable c306l    "Method provided/ prescribed:Emergency contraception"
label variable c306o    "Method provided/ prescribed:Natural methods/Periodic abstinence (PA)"
label variable c306p    "Method provided/ prescribed:LAM/breastfeeding"
label variable c306q    "Method provided/ prescribed:Vasectomy"
label variable c306r    "Method provided/ prescribed:Female sterilization"
label variable c306s    "Method provided/ prescribed:Cycle beads for SDM"
label variable c306x    "Method provided/ prescribed:Other"
label variable c306y    "Method provided/ prescribed:No method"
label variable c307a    "Information for pills or injections:How often/ when to take"
label variable c307b    "Information for pills or injections:Menstrual changes"
label variable c307c    "Information for pills or injections:Initial side effects"
label variable c307d    "Information for pills or injections:What to do if forget pill or delay injection"
label variable c307e    "Information for pills or injections:Method does not protect from STIs including "
label variable c307f    "Information for pills or injections:Should return to clinic if side effects pers"
label variable c307y    "Information for pills or injections:No information for users of pills/ injection"
label variable c308a    "Information for implant:Good for 3-5 years"
label variable c308b    "Information for implant:Menstrual changes"
label variable c308c    "Information for implant:Initial side effects"
label variable c308d    "Information for implant: Method does not protect against STIs including HIV"
label variable c308e    "Information for implant: Return if side effects persist"
label variable c308y    "Information for implant: No information for users of implant"
label variable c309a    "Information for condoms:Cannot use if allergic to latex"
label variable c309b    "Information for condoms:Can be used only once"
label variable c309c    "Information for condoms:Lubricants may be used"
label variable c309d    "Information for condoms:Use as backup"
label variable c309e    "Information for condoms:Dual protection"
label variable c309y    "Information for condoms:No information for users of condom"
label variable c310a    "NA - Information for IUCD:Check string after menstruation"
label variable c310b    "NA - Information for IUCD:May cause heavy bleeding or spotting"
label variable c310c    "NA - Information for IUCD:Good for up to 5 or 12 years"
label variable c310d    "NA - Information for IUCD:Return 3-6 weeks post insertion/after first menses"
label variable c310e    "NA - Information for IUCD:Return if side effects continue"
label variable c310f    "NA - Information for IUCD:Method does not protect against STIs including HIV"
label variable c310y    "NA - Information for IUCD:No information for users of IUCD"
label variable c311a    "NA - Information for emergency contraception:Need 2nd dose if vomit within 2 hou"
label variable c311b    "NA - Information for emergency contraception:Late or light period, return for pr"
label variable c311c    "NA - ** Information for emergency contraception:First dose within 120 hours of c"
label variable c311d    "NA - Information for emergency contraception:Second dose 12 hours after 1st dose"
label variable c311e    "NA - Information for emergency contraception:Do not repeat more often than 3 tim"
label variable c311f    "NA - Information for emergency contraception:Method does not protect against STI"
label variable c311y    "NA - Information for emergency contraception:No information for users of emergen"
label variable c313a    "Information for periodic abstinence (PA):How to identify fertile period"
label variable c313b    "Information for periodic abstinence (PA):No intercourse during fertile period wi"
label variable c313c    "Information for periodic abstinence (PA):Method does not protect against STIs in"
label variable c313y    "Information for periodic abstinence (PA):No information for users of PA"
label variable c314a    "Information for LAM:Slight risk of pregnancy during time before menstruation res"
label variable c314b    "Information for LAM:Most effective with exclusive breastfeeding without menstrua"
label variable c314c    "Information for LAM:Not effective after menstruation resumes"
label variable c314d    "Information for LAM:Method does not protect against STIs including HIV"
label variable c314e    "Information for LAM:Infant must be less than 6 months of age"
label variable c314y    "Information for LAM:No information for users of LAM"
label variable c315a    "NA - Information for sterilization (male and female):Intended to be permanent, s"
label variable c315c    "NA - Information for sterilization (male):Use of back-up method for 3 months aft"
label variable c315d    "NA - Information for sterilization (male):Partner is protected from pregnancy af"
label variable c315e    "NA - Information for sterilization (female):Protected from pregnancy immediately"
label variable c315f    "NA - Information for sterilization (male and female):Warning signs that may occu"
label variable c315g    "NA - Information for sterilization (male and female):Should return to clinic if "
label variable c315h    "NA - Information for sterilization (male and female):Method does not protect aga"
label variable c315y    "NA - Information for sterilization (male and female):No information for users of"
label variable c316     "Provider wrote on client health card"
label variable c317     "Provider used visual aids"
label variable c318     "Provider discussed return visit"
label variable c319     "Clinical procedure:same provider or different"
label variable c320     "Clinical procedure:type of provider"
label variable c321     "Clinical procedure:sex of provider"
label variable c322     "Pelvic exam performed"
label variable c323a    "Before pelvic exam:Ensure visual privacy"
label variable c323b    "Before pelvic exam:Ensure auditory privacy"
label variable c323c    "Before pelvic exam:Explain procedure before starting"
label variable c323d    "Before pelvic exam:Prepare all instruments before procedure"
label variable c323e    "During pelvic exam:Use sterilized/HLD instruments"
label variable c323f    "Before pelvic exam:Wash hands with soap before examination"
label variable c323g    "Before pelvic exam:Put on new or disinfected latex gloves before examination"
label variable c323h    "During pelvic exam:Ask client to relax muscles"
label variable c323i    "During pelvic exam:Inspect external genitalia"
label variable c323j    "During pelvic exam:Explain speculum procedure (if used)"
label variable c323k    "During pelvic exam:Inspect cervix and vaginal mucosa"
label variable c323l    "During pelvic exam:Perform bimanual exam"
label variable c323m1   "After pelvic exam:Removed gloves"
label variable c323m    "After pelvic exam:Wash hands after removing gloves"
label variable c323n    "After pelvic exam:Wipe contaminated surfaces with disinfectant"
label variable c323o    "After pelvic exam:Placed used instruments in disinfectant solution immediately a"
label variable c324     "IUCD procedures performed"
label variable c325a    "NA - Before IUCD procedures:Ensure visual privacy"
label variable c325b    "NA - Before IUCD procedures:Ensure auditory privacy"
label variable c325c    "NA - Before IUCD procedures:Explain procedure before starting"
label variable c325d    "NA - Before IUCD procedures:Reconfirm choice (with new client)"
label variable c325e    "NA - Before IUCD procedures:Verify client not pregnant (with new client)"
label variable c325f    "NA - Before IUCD procedures:Prepare all instruments"
label variable c325g    "NA - During IUCD procedures:Use sterilized/HLD instruments"
label variable c325h    "NA - Before IUCD procedures:Wash hands with soap before procedure"
label variable c325i    "NA - Before IUCD procedures:Put on new/disinfected latex gloves"
label variable c325i2   "NA - Before IUCD procedures:Clean cervix and vagina with antiseptic"
label variable c325j    "NA - During IUCD procedures:Perform speculum exam for RTIs or STIs before bimanu"
label variable c325k    "NA - During IUCD procedures:Perform bimanual exam"
label variable c325l    "NA - During IUCD procedures:Inspect cervix and vaginal mucosa"
label variable c325m    "NA - During IUCD procedures:Use a tenaculum"
label variable c325n    "NA - During IUCD procedures:Sound uterus before inserting IUCD"
label variable c325n2   "NA - During IUCD procedures:explained any of the above procedures"
label variable c325o    "NA - During IUCD procedures:Use no-touch technique for inserting IUCD"
label variable c325o2   "NA - After IUCD procedures:Remove gloves"
label variable c325p    "NA - After IUCD procedures:Wash hands after removing gloves"
label variable c325q    "NA - After IUCD procedures:Ask client to wait and rest for 15 minutes after inse"
label variable c325r    "NA - After IUCD procedures:Wipe contaminated surfaces with disinfectant"
label variable c325s    "NA - After IUCD procedures:Placed used instruments in disinfectant solution imme"
label variable c325t    "NA - IUCD procedures:Instructed client to check string"
label variable c325u    "NA - IUCD procedures:Told client about spotting/bleeding"
label variable c325v    "NA - * IUCD procedures:Told good for up to 5-12 years (*** Haiti - up to 12 mont"
label variable c325w    "NA - IUCD procedures:Instructed to return in 3-6 weeks"
label variable c325xa   "NA - IUCD procedures:Instructed to return if side effects continue"
label variable c325xb   "NA - IUCD procedures:Client provided with card stating date of insertion and fol"
label variable c325xc   "NA - IUCD procedures:(If IUCD removed) Showed the removed IUCD to client"
label variable c325y    "NA - IUCD procedures:No client-provider interaction regarding instructions"
label variable c326     "Contraceptive injection given"
label variable c327a    "Before injection:Reconfirm choice (with new client)"
label variable c327b    "Before injection:Verify client not pregnant (with new client)"
label variable c327c    "Before injection:Check client card to ensure correct timing"
label variable c327c2   "Before injection:Ensured visual privacy"
label variable c327c3   "Before injection:Ensure auditory privacy"
label variable c327d    "Before injection:Wash hands with soap before giving injection"
label variable c327d2   "Before injection:Prepare injection in clean location"
label variable c327e    "During injection procedure:Use new syringe and needle from sterile sealed pack ("
label variable c327e2   "During injection procedure:Provider observed opening new packet"
label variable c327f    "During injection procedure:Remove needle from multiple dose vial"
label variable c327g    "During injection procedure:Stir/mix bottle before drawing dose (DEPO)"
label variable c327h    "During injection procedure:Clean/air-dry the injection site before injection"
label variable c327i    "During injection procedure:Draw back plunger before giving injection"
label variable c327j    "During injection procedure:Allow dose to self-disperse (no massage)"
label variable c327k    "After injection:Dispose of sharps in puncture-resistant container"
label variable c327l    "NA - After injection:Tell client not to massage injection site"
label variable c327m    "NA - After injection:Tell client when to return for next injection"
label variable c328     "Needle/syringe provided by facility or client"
label variable c329     "Implant procedure"
label variable c330a    "Before Implant procedure:Reconfirm choice (with new client)"
label variable c330b    "Before Implant procedure:Verify client not pregnant (with new client)"
label variable c330c    "Before Implant procedure:Ensure visual privacy"
label variable c330d    "Before Implant procedure:Ensure auditory privacy"
label variable c330e    "Before Implant procedure:Explain procedure before starting"
label variable c330f    "Before Implant procedure:Prepare instruments before procedure"
label variable c330g    "During Implant procedure:Use sterilized or HLD instruments"
label variable c330h    "Before Implant procedure:Wash hands with soap before procedure"
label variable c330i    "Before Implant procedure:Put on sterile gloves/maintain sterility during inserti"
label variable c330j    "During Implant procedure:Clean skin with antiseptic"
label variable c330k    "During Implant procedure:Use sterile towel to protect area"
label variable c330l    "During Implant procedure:New or sterilized needle and syringe for local anesthet"
label variable c330m    "During Implant procedure:Allow time for anesthetic to work"
label variable c330n    "After Implant procedure:Dispose of sharps in puncture-resistant container"
label variable c330o    "After Implant procedure:Disinfect area"
label variable c330p    "After Implant procedure:Places used instruments in disinfectant solution immedia"
label variable c330p2   "After Implant procedure:Remove gloves"
label variable c330q    "After Implant procedure:Wash hands after removing gloves"
label variable c330r    "After Implant procedure:Explain incision care and removal of bandage"
label variable c330s    "After Implant procedure:Discuss return visit to remove plaster"
label variable c330t    "Implant procedure:Provide card with date of implant and date of expiration"
label variable c330u    "Implant procedure:Reinforce expectations about side effects"
label variable c330v    "Implant procedure:(In case of removal) Showed each removed implant stick"
label variable c330w    "Implant procedure:Told about menstrual changes"
label variable c330xa   "Implant procedure:Client instructed that implant is good for 3-5 years"
label variable c330xb   "Implant procedure:Client instructed to return if side effects persist"
label variable c331     "Needle/syringe for implant provided by facility or client"
label variable c340     "Family planning status at beginning of consult"
label variable c341     "Principal reason for visit"
label variable c342     "Current user: outcome of visit"
label variable c345     "Not current user: outcome of visit"
label variable c346     "Client left with method"
label variable c347     "Reason client left with no method"
label variable c348     "Provider updated client record"
label variable c351     "Doing something to avoid pregnancy before today"
label variable c352a    "FP method used current/last 6 months:Combined pill"
label variable c352b    "FP method used current/last 6 months:Progestin-only pill"
label variable c352c    "FP method used current/last 6 months:Pill (type unspecified)"
label variable c352d    "FP method used current/last 6 months:Injectable (1 mo)"
label variable c352e    "FP method used current/last 6 months:Injectable (2-3 month)"
label variable c352f    "NA - FP method used current/last 6 months:Injectable (type unspecified)"
label variable c352g    "FP method used current/last 6 months:Implant"
label variable c352h    "NA - FP method used current/last 6 months:Implant 2nd type"
label variable c352i    "FP method used current/last 6 months:Male condom"
label variable c352j    "FP method used current/last 6 months:Female condom"
label variable c352k    "FP method used current/last 6 months:IUCD"
label variable c352l    "FP method used current/last 6 months:Emergency Contraception"
label variable c352o    "FP method used current/last 6 months:Periodic abstinence (PA)"
label variable c352p    "FP method used current/last 6 months:LAM"
label variable c352q    "FP method used current/last 6 months:Vasectomy"
label variable c352r    "FP method used current/last 6 months:Female sterilization"
label variable c352s    "FP method used current/last 6 months:Cycle beads for SDM"
label variable c352x    "FP method used current/last 6 months:Other"
label variable c353a    "Problem with method: Provider asked if problem existed"
label variable c353b    "Problem with method: Client is having a problem with method"
label variable c353b2   "Problem with method: Client mentioned problem to provider"
label variable c353c    "Problem with method: Provider suggested an action to resolve it"
label variable c354     "Client's outcome of visit"
label variable c355     "Client considered switching to new method"
label variable c356     "New user thought about method to start"
label variable c357a    "FP method considered before today's visit:Combined pill"
label variable c357b    "FP method considered before today's visit:Progestin-only pill"
label variable c357c    "FP method considered before today's visit:Pill (type unspecified)"
label variable c357d    "FP method considered before today's visit:Injectable (1 month)"
label variable c357e    "FP method considered before today's visit:Injectable (2-3 month)"
label variable c357f    "NA - FP method considered before today's visit:Injectable (type unspecified)"
label variable c357g    "FP method considered before today's visit:Implant"
label variable c357h    "NA - FP method considered before today's visit:Implant 2nd type"
label variable c357i    "FP method considered before today's visit:Male condom"
label variable c357j    "FP method considered before today's visit:Female condom"
label variable c357k    "FP method considered before today's visit:IUCD"
label variable c357l    "FP method considered before today's visit:Emergency Contraception"
label variable c357o    "FP method considered before today's visit:Periodic abstinence (PA)"
label variable c357p    "FP method considered before today's visit:LAM"
label variable c357q    "FP method considered before today's visit:Vasectomy"
label variable c357r    "FP method considered before today's visit:Female sterilization"
label variable c357s    "FP method considered before today's visit:Cycle beads for SDM"
label variable c357x    "FP method considered before today's visit:Other"
label variable c358     "Provider talked about any considered methods"
label variable c359a    "FP method provider talked about:Combined pill"
label variable c359b    "FP method provider talked about:Progestin-only pill"
label variable c359c    "FP method provider talked about:Pill (type unspecified)"
label variable c359d    "FP method provider talked about:Injectable (1 mo)"
label variable c359e    "FP method provider talked about:Injectable (2-3 mo)"
label variable c359f    "NA - FP method provider talked about:Injectable (type unspecified)"
label variable c359g    "FP method provider talked about:Implant"
label variable c359h    "NA - FP method provider talked about:Implant 2nd type"
label variable c359i    "FP method provider talked about:Male condom"
label variable c359j    "FP method provider talked about:Female condom"
label variable c359k    "FP method provider talked about:IUD"
label variable c359l    "FP method provider talked about:Emergency Contraception"
label variable c359o    "FP method provider talked about:Periodic abstinence (PA)"
label variable c359p    "FP method provider talked about:LAM/ breastfeeding"
label variable c359q    "FP method provider talked about:Vasectomy"
label variable c359r    "FP method provider talked about:Female sterilization"
label variable c359s    "FP method provider talked about:Cycle beads for SDM"
label variable c359x    "FP method provider talked about:Other"
label variable c360a    "FP method received/prescribed today:Combined pill"
label variable c360b    "FP method received/prescribed today:Progestin-only pill"
label variable c360c    "FP method received/prescribed today:Pill (type unspecified)"
label variable c360d    "FP method received/prescribed today:Combined injection (1 month)"
label variable c360e    "FP method received/prescribed today:Injection progestin only ((2-3 mo - ex:Depo)"
label variable c360f    "NA - FP method received/prescribed today:Injection (type unspecified)"
label variable c360g    "FP method received/prescribed today:Implant"
label variable c360h    "NA - FP method received/prescribed today:Implant 2nd type"
label variable c360i    "FP method received/prescribed today:Male condom"
label variable c360j    "FP method received/prescribed today:Female condom"
label variable c360k    "FP method received/prescribed today:IUCD"
label variable c360l    "FP method received/prescribed today:Emergency Contraception"
label variable c360o    "FP method received/prescribed today:Periodic abstinence (PA)"
label variable c360p    "FP method received/prescribed today:LAM/breastfeeding"
label variable c360q    "FP method received/prescribed today:Male sterilization"
label variable c360r    "FP method received/prescribed today:Female sterilization"
label variable c360s    "FP method received/prescribed today:Cycle beads for SDM"
label variable c360x    "FP method received/prescribed today:Other"
label variable c360y    "FP method received/prescribed today:No method"
label variable c361     "FP method protects against STI and HIV/AIDS"
label variable c362a    "During consult, provider:Explained how to use method"
label variable c362b    "During consult, provider:Talked about possible side effects"
label variable c362c    "During consult, provider:Advised what to do if problems occurred"
label variable c362d    "During consult, provider:Told when to return for follow-up"
label variable c363a    "Method-related question:(pill) Take pill daily"
label variable c363d    "Method-related question:(Injectable combined) Duration of protection one month"
label variable c363e    "Method-related question:(Injectable progestin-only) Duration of protection 2-3 m"
label variable c363g    "*Method-related question:(Implant) Duration of protection 3-5 years (Haiti - 3-7"
label variable c363i    "Method-related question:(Male condom) Can be used only once"
label variable c363j    "NA - Method-related question:(Female condom) Type of lubricant that can be used"
label variable c363j2   "Method-related question:CS (Female condom) Can be used only once"
label variable c363k    "NA - Method-related question:(IUCD) Check string to make sure IUCD in place"
label variable c363o1   "Method-related question:(Per abst/SDM) Fertile - body temperature rises"
label variable c363o2   "Method-related question:(Per abst/SDM) Fertile - mucus in vagina"
label variable c363o3   "Method-related question:(Per abst/SDM) Fertile - Days 12-16 of cycle"
label variable c363o3a  "Method-related question:(Per abst/SDM) Fertile - White bead days/ Days 8-19 of c"
label variable c363o4   "Method-related question:(Per abst/SDM) Fertile - Other"
label variable c363o5   "Method-related question:(Per abst/SDM) Fertile - Don't know"
label variable c363p    "NA - Method-related question:(LAM) Can use method if menses resumes?"
label variable c363q1   "NA - Method-related question:(Vasectomy) After sterilization, how long to wait f"
label variable c363q2   "NA - Method-related question:CS (Vasectomy) After sterilization (& 3 mos) can im"
label variable c363r1   "NA - Method-related question:(Female sterilization)  After sterilization, how lo"
label variable c363r2   "NA - Method-related question:CS (Female sterilization) After sterilization, can "
label variable sxf107a  "CS - Specific problem with method being used: Nausea"
label variable sxf107b  "CS - Specific problem with method being used: Headache"
label variable sxf107c  "CS - Specific problem with method being used: Spotting"
label variable sxf107d  "CS - Specific problem with method being used: Hemhorraging"
label variable sxf107e  "CS - Specific problem with method being used: Absence of menstrual period"
label variable sxf107f  "CS - Specific problem with method being used: Cramps"
label variable sxf107g  "CS - Specific problem with method being used: Heavy menstruation"
label variable sxf107h  "CS - Specific problem with method being used: Infection"
label variable sxf107i  "CS - Specific problem with method being used: Rejected"
label variable sxf107j  "CS - Specific problem with method being used: Forgot to use"
label variable sxf107x  "CS - Specific problem with method being used: Other"

#delimit ;
label define C001    
     1 "West"
     2 "Southeast"
     3 "North"
     4 "Northeast"
     5 "Artibonite"
     6 "Central"
     7 "South"
     8 "Grand-Anse"
     9 "Northwest"
    10 "Nippes"
;
label define C003    
     1 "Urban"
     2 "Rural"
;
label define C007    
     1 "University hospital"
     2 "Regional hospital"
     3 "Community referral hospital"
     4 "Hospital"
     5 "Health center with LIT"
     6 "Health center without LIT"
     7 "Dispensary"
;
label define C008    
     1 "Government/public"
     2 "NGO/ Private not for profit"
     3 "Private for profit"
     4 "Mission/ faith-based"
;
label define C020A   
     0 "Refused by provider or client"
     1 "Complete"
     7 "Not returned from field"
;
label define C020B   
     0 "Refused by client"
     1 "Complete"
     2 "Sick child admitted, not possible to continue"
     7 "Not returned from field"
;
label define C021    
     1 "ANC"
     2 "Child Sick"
     3 "Family Planning"
     6 "CS - Labor/Delivery"
;
label define C022    
     1 "Male"
     2 "Female"
;
label define C023    
     1 "Male"
     2 "Female"
;
label define C024    
     1 "Medical doctor (generalist)"
     2 "Surgeon (general)"
     3 "Medical specialist"
    21 "Nurse"
    22 "Nurse/midwife"
    23 "Auxiliary nurse"
    35 "Lab technician, medical technologist"
    71 "Auxiliary dentist"
    72 "Other community health workers"
    95 "Non-technical qualification"
    96 "Other"
;
label define C501    
     0 "Saw provider immediately"
   998 "Don't know"
;
label define C502A   
     0 "No problem"
     1 "Large problem"
     2 "Small problem"
     8 "Don't know"
;
label define C502B   
     0 "No problem"
     1 "Large problem"
     2 "Small problem"
     8 "Don't know"
;
label define C502C   
     0 "No problem"
     1 "Large problem"
     2 "Small problem"
     8 "Don't know"
;
label define C502E   
     0 "No problem"
     1 "Large problem"
     2 "Small problem"
     8 "Don't know"
;
label define C502F   
     0 "No problem"
     1 "Large problem"
     2 "Small problem"
     8 "Don't know"
;
label define C502G   
     0 "No problem"
     1 "Large problem"
     2 "Small problem"
     8 "Don't know"
;
label define C502H   
     0 "No problem"
     1 "Large problem"
     2 "Small problem"
     8 "Don't know"
;
label define C502I   
     0 "No problem"
     1 "Large problem"
     2 "Small problem"
     8 "Don't know"
;
label define C502J   
     0 "No problem"
     1 "Large problem"
     2 "Small problem"
     8 "Don't know"
;
label define C502K   
     0 "No problem"
     1 "Large problem"
     2 "Small problem"
     8 "Don't know"
;
label define C502L   
     0 "No problem"
     1 "Large problem"
     2 "Small problem"
     8 "Don't know"
;
label define C503    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define C504    
     0 "No"
     1 "Yes"
;
label define C505    
999998 "Don't know"
;
label define C507    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define C508    
     1 "Inconvenient operating hours"
     2 "Bad reputation"
     3 "Don't like personnel"
     4 "No medicine"
     5 "Prefers to remain anonymous"
     6 "More expensive"
     7 "Referral"
    96 "Other"
    98 "Don't know"
;
label define C510    
     1 "Mother"
     2 "Father"
     3 "Sibling"
     4 "Aunt or uncle"
     5 "Grandparent"
     6 "Other"
;
label define C511    
    98 "Don't know"
;
label define C512    
     0 "Never attended school"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
;
label define C514    
     0 "Cannot read or write"
     1 "Read only"
     2 "Read and write"
     8 "Don;t know"
;
label define C515    
     0 "No schooling"
     1 "Primary"
     2 "Post primary/technical"
     3 "Secondary"
     4 "Higher/University"
;
label define C517A   
  9797 "Inconsistent"
  9898 "Don't know"
;
label define C517B   
  9797 "Inconsistent"
  9898 "Don't know"
;
label define C518A   
  9797 "Inconsistent"
  9898 "Don't know"
;
label define C518B   
  9797 "Inconsistent"
  9898 "Don't know"
;
label define C520    
     1 "Very satisfied"
     2 "Somewhat satisfied"
     3 "Not satisfied"
;
label define C521    
     0 "No"
     1 "Yes"
     8 "DK"
;
label define C522    
     0 "No or incomplete observation"
     1 "Yes"
     2 "More than 1 reported as first"
;
label define SCDEPART
     0 "West Metropolitan"
     1 "Other west"
     2 "Southeast"
     3 "North"
     4 "Northeast"
     5 "Artibonite"
     6 "Central"
     7 "South"
     8 "Grand-Anse"
     9 "Northwest"
    10 "Nippes"
;
label define SCLOCAL 
     1 "Metropolitan"
     2 "Other urban"
     3 "Rural"
;
label define C301A   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define C301B   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define C302A   
     0 "No"
     1 "Yes"
;
label define C302B   
     0 "No"
     1 "Yes"
;
label define C302C   
     0 "No"
     1 "Yes"
;
label define C302E   
     0 "No"
     1 "Yes"
;
label define C302F   
     0 "No"
     1 "Yes"
;
label define C302G   
     0 "No"
     1 "Yes"
;
label define C302H   
     0 "No"
     1 "Yes"
;
label define C302I   
     0 "No"
     1 "Yes"
;
label define C302Y1  
     0 "No"
     1 "Yes, no client history for all clients"
;
label define C302Y2  
     0 "No"
     1 "Yes, no client history for female clients"
;
label define C303A   
     0 "No"
     1 "Yes"
;
label define C303B   
     0 "No"
     1 "Yes"
;
label define C303C   
     0 "No"
     1 "Yes"
;
label define C303D   
     0 "No"
     1 "Yes"
;
label define C303E   
     0 "No"
     1 "Yes"
;
label define C303F   
     0 "No"
     1 "Yes"
;
label define C303G   
     0 "No"
     1 "Yes"
;
label define C303Y   
     0 "No"
     1 "Yes, no physical exam/ health questions"
;
label define CF303A  
     0 "Activity not routinely done"
     1 "Observed"
     2 "Reported, not seen"
     8 "Don't know"
;
label define CF303B  
     0 "Activity not routinely done"
     1 "Observed"
     2 "Reported, not seen"
     8 "Don't know"
;
label define CF303XA 
     0 "Activity not routinely done"
     1 "Observed"
     2 "Reported, not seen"
     8 "Don't know"
;
label define C304A   
     0 "No"
     1 "Yes"
;
label define C304B   
     0 "No"
     1 "Yes"
;
label define C304C   
     0 "No"
     1 "Yes"
;
label define C304Y   
     0 "No"
     1 "Yes, no privacy issues observed"
;
label define C305A   
     0 "No"
     1 "Yes"
;
label define C305B   
     0 "No"
     1 "Yes"
;
label define C305C   
     0 "No"
     1 "Yes"
;
label define C305D   
     0 "No"
     1 "Yes"
;
label define C305E   
     0 "No"
     1 "Yes"
;
label define C305F   
     0 "No"
     1 "Yes"
;
label define C305G   
     0 "No"
     1 "Yes"
;
label define C305Y   
     0 "No"
     1 "Yes, no discussion of issues observed"
;
label define C306A   
     0 "No"
     1 "Yes, provided"
     2 "Yes, prescribed to be filled later/ different location"
;
label define C306B   
     0 "No"
     1 "Yes, provided"
     2 "Yes, prescribed to be filled later/ different location"
;
label define C306C   
     0 "No"
     1 "Yes, provided"
     2 "Yes, prescribed to be filled later/ different location"
;
label define C306D   
     0 "No"
     1 "Yes, provided"
     2 "Yes, prescribed to be filled later/ different location"
;
label define C306E   
     0 "No"
     1 "Yes, provided"
     2 "Yes, prescribed to be filled later/ different location"
;
label define C306F   
     0 "No"
     1 "Yes, provided"
     2 "Yes, prescribed to be filled later/ different location"
;
label define C306G   
     0 "No"
     1 "Yes, provided"
     2 "Yes, prescribed to be filled later/ different location"
;
label define C306H   
     0 "No"
     1 "Yes, provided"
     2 "Yes, prescribed to be filled later/ different location"
;
label define C306I   
     0 "No"
     1 "Yes, provided"
     2 "Yes, prescribed to be filled later/ different location"
;
label define C306J   
     0 "No"
     1 "Yes, provided"
     2 "Yes, prescribed to be filled later/ different location"
;
label define C306K   
     0 "No"
     1 "Yes, provided"
     2 "Yes, prescribed to be filled later/ different location"
;
label define C306L   
     0 "No"
     1 "Yes, provided"
     2 "Yes, prescribed to be filled later/ different location"
;
label define C306O   
     0 "No"
     1 "Yes, provided"
     2 "Yes, prescribed to be filled later/ different location"
;
label define C306P   
     0 "No"
     1 "Yes, provided"
     2 "Yes, prescribed to be filled later/ different location"
;
label define C306Q   
     0 "No"
     1 "Yes, provided"
     2 "Yes, prescribed to be filled later/ different location"
;
label define C306R   
     0 "No"
     1 "Yes, provided"
     2 "Yes, prescribed to be filled later/ different location"
;
label define C306S   
     0 "No"
     1 "Yes, provided"
     2 "Yes, prescribed to be filled later/ different location"
;
label define C306X   
     0 "No"
     1 "Yes, provided"
     2 "Yes, prescribed to be filled later/ different location"
;
label define C306Y   
     0 "No, something provided or prescribed"
     1 "Yes nothing provided or precribed"
;
label define C307A   
     0 "No"
     1 "Yes"
;
label define C307B   
     0 "No"
     1 "Yes"
;
label define C307C   
     0 "No"
     1 "Yes"
;
label define C307D   
     0 "No"
     1 "Yes"
;
label define C307E   
     0 "No"
     1 "Yes"
;
label define C307F   
     0 "No"
     1 "Yes"
;
label define C307Y   
     0 "No"
     1 "Yes, no information for user"
;
label define C308A   
     0 "No"
     1 "Yes"
;
label define C308B   
     0 "No"
     1 "Yes"
;
label define C308C   
     0 "No"
     1 "Yes"
;
label define C308D   
     0 "No"
     1 "Yes"
;
label define C308E   
     0 "No"
     1 "Yes"
;
label define C308Y   
     0 "No"
     1 "Yes, no information for user"
;
label define C309A   
     0 "No"
     1 "Yes"
;
label define C309B   
     0 "No"
     1 "Yes"
;
label define C309C   
     0 "No"
     1 "Yes"
;
label define C309D   
     0 "No"
     1 "Yes"
;
label define C309E   
     0 "No"
     1 "Yes"
;
label define C309Y   
     0 "No"
     1 "Yes, no information for user"
;
label define C310A   
     0 "No"
     1 "Yes"
;
label define C310B   
     0 "No"
     1 "Yes"
;
label define C310C   
     0 "No"
     1 "Yes"
;
label define C310D   
     0 "No"
     1 "Yes"
;
label define C310E   
     0 "No"
     1 "Yes"
;
label define C310F   
     0 "No"
     1 "Yes"
;
label define C310Y   
     0 "No"
     1 "Yes, no information for user"
;
label define C311A   
     0 "No"
     1 "Yes"
;
label define C311B   
     0 "No"
     1 "Yes"
;
label define C311C   
     0 "No"
     1 "Yes"
;
label define C311D   
     0 "No"
     1 "Yes"
;
label define C311E   
     0 "No"
     1 "Yes"
;
label define C311F   
     0 "No"
     1 "Yes"
;
label define C311Y   
     0 "No"
     1 "Yes, no information for user"
;
label define C313A   
     0 "No"
     1 "Yes"
;
label define C313B   
     0 "No"
     1 "Yes"
;
label define C313C   
     0 "No"
     1 "Yes"
;
label define C313Y   
     0 "No"
     1 "Yes, no information for user"
;
label define C314A   
     0 "No"
     1 "Yes"
;
label define C314B   
     0 "No"
     1 "Yes"
;
label define C314C   
     0 "No"
     1 "Yes"
;
label define C314D   
     0 "No"
     1 "Yes"
;
label define C314E   
     0 "No"
     1 "Yes"
;
label define C314Y   
     0 "No"
     1 "Yes, no information for user"
;
label define C315A   
     0 "No"
     1 "Yes"
;
label define C315C   
     0 "No"
     1 "Yes"
;
label define C315D   
     0 "No"
     1 "Yes"
;
label define C315E   
     0 "No"
     1 "Yes"
;
label define C315F   
     0 "No"
     1 "Yes"
;
label define C315G   
     0 "No"
     1 "Yes"
;
label define C315H   
     0 "No"
     1 "Yes"
;
label define C315Y   
     0 "No"
     1 "Yes, no information for user"
;
label define C316    
     0 "No"
     1 "Yes"
;
label define C317    
     0 "No"
     1 "Yes"
;
label define C318    
     0 "No"
     1 "Yes"
;
label define C319    
     0 "No clinical procedure"
     1 "Yes, same provider"
     2 "Yes, different provider agreed"
     3 "Yes, different provider refused"
;
label define C320    
     1 "Medical doctor (generalist)"
     2 "Surgeon (general)"
     3 "Medical specialist"
    21 "Nurse"
    22 "Nurse/midwife"
    23 "Auxiliary nurse"
    35 "Lab technician, medical technologist"
    71 "Auxiliary dentist"
    72 "Other community health workers"
    95 "Non-technical qualification"
    96 "Other"
;
label define C321    
     1 "Male"
     2 "Female"
;
label define C322    
     0 "No"
     1 "Yes"
;
label define C323A   
     0 "No"
     1 "Yes"
;
label define C323B   
     0 "No"
     1 "Yes"
;
label define C323C   
     0 "No"
     1 "Yes"
;
label define C323D   
     0 "No"
     1 "Yes"
;
label define C323E   
     0 "No"
     1 "Yes"
;
label define C323F   
     0 "No"
     1 "Yes"
;
label define C323G   
     0 "No"
     1 "Yes"
;
label define C323H   
     0 "No"
     1 "Yes"
;
label define C323I   
     0 "No"
     1 "Yes"
;
label define C323J   
     0 "No"
     1 "Yes"
;
label define C323K   
     0 "No"
     1 "Yes"
;
label define C323L   
     0 "No"
     1 "Yes"
;
label define C323M1  
     0 "No"
     1 "Yes"
;
label define C323M   
     0 "No"
     1 "Yes"
;
label define C323N   
     0 "No"
     1 "Yes"
;
label define C323O   
     0 "No"
     1 "Yes"
;
label define C324    
     0 "No"
     1 "Yes,Removed and inserted"
     2 "Yes,Inserted only"
     3 "Yes,Removed only"
     4 "IUD inspected only"
;
label define C325A   
     0 "No"
     1 "Yes"
;
label define C325B   
     0 "No"
     1 "Yes"
;
label define C325C   
     0 "No"
     1 "Yes"
;
label define C325D   
     0 "No"
     1 "Yes"
;
label define C325E   
     0 "No"
     1 "Yes"
;
label define C325F   
     0 "No"
     1 "Yes"
;
label define C325G   
     0 "No"
     1 "Yes"
;
label define C325H   
     0 "No"
     1 "Yes"
;
label define C325I   
     0 "No"
     1 "Yes"
;
label define C325I2  
     0 "No"
     1 "Yes"
;
label define C325J   
     0 "No"
     1 "Yes"
;
label define C325K   
     0 "No"
     1 "Yes"
;
label define C325L   
     0 "No"
     1 "Yes"
;
label define C325M   
     0 "No"
     1 "Yes"
;
label define C325N   
     0 "No"
     1 "Yes"
;
label define C325N2  
     0 "No"
     1 "Yes"
;
label define C325O   
     0 "No"
     1 "Yes"
;
label define C325O2  
     0 "No"
     1 "Yes"
;
label define C325P   
     0 "No"
     1 "Yes"
;
label define C325Q   
     0 "No"
     1 "Yes"
;
label define C325R   
     0 "No"
     1 "Yes"
;
label define C325S   
     0 "No"
     1 "Yes"
;
label define C325T   
     0 "No"
     1 "Yes"
;
label define C325U   
     0 "No"
     1 "Yes"
;
label define C325V   
     0 "No"
     1 "Yes"
;
label define C325W   
     0 "No"
     1 "Yes"
;
label define C325XA  
     0 "No"
     1 "Yes"
;
label define C325XB  
     0 "No"
     1 "Yes"
;
label define C325XC  
     0 "No"
     1 "Yes"
;
label define C325Y   
     0 "No"
     1 "Yes, none observed"
;
label define C326    
     0 "No"
     1 "Yes"
;
label define C327A   
     0 "No"
     1 "Yes"
;
label define C327B   
     0 "No"
     1 "Yes"
;
label define C327C   
     0 "No"
     1 "Yes"
;
label define C327C2  
     0 "No"
     1 "Yes"
;
label define C327C3  
     0 "No"
     1 "Yes"
;
label define C327D   
     0 "No"
     1 "Yes"
;
label define C327D2  
     0 "No"
     1 "Yes"
;
label define C327E   
     0 "No"
     1 "Yes"
;
label define C327E2  
     0 "No"
     1 "Yes"
;
label define C327F   
     0 "No"
     1 "Yes"
;
label define C327G   
     0 "No"
     1 "Yes"
;
label define C327H   
     0 "No"
     1 "Yes"
;
label define C327I   
     0 "No"
     1 "Yes"
;
label define C327J   
     0 "No"
     1 "Yes"
;
label define C327K   
     0 "No"
     1 "Yes"
;
label define C327L   
     0 "No"
     1 "Yes"
;
label define C327M   
     0 "No"
     1 "Yes"
;
label define C328    
     1 "Provided by facility"
     2 "Provided by client"
     8 "Don't know"
;
label define C329    
     0 "No"
     1 "Yes,removal and insertion"
     2 "Yes,insertion only"
     3 "Yes,removal only"
;
label define C330A   
     0 "No"
     1 "Yes"
;
label define C330B   
     0 "No"
     1 "Yes"
;
label define C330C   
     0 "No"
     1 "Yes"
;
label define C330D   
     0 "No"
     1 "Yes"
;
label define C330E   
     0 "No"
     1 "Yes"
;
label define C330F   
     0 "No"
     1 "Yes"
;
label define C330G   
     0 "No"
     1 "Yes"
;
label define C330H   
     0 "No"
     1 "Yes"
;
label define C330I   
     0 "No"
     1 "Yes"
;
label define C330J   
     0 "No"
     1 "Yes"
;
label define C330K   
     0 "No"
     1 "Yes"
;
label define C330L   
     0 "No"
     1 "Yes"
;
label define C330M   
     0 "No"
     1 "Yes"
;
label define C330N   
     0 "No"
     1 "Yes"
;
label define C330O   
     0 "No"
     1 "Yes"
;
label define C330P   
     0 "No"
     1 "Yes"
;
label define C330P2  
     0 "No"
     1 "Yes"
;
label define C330Q   
     0 "No"
     1 "Yes"
;
label define C330R   
     0 "No"
     1 "Yes"
;
label define C330S   
     0 "No"
     1 "Yes"
;
label define C330T   
     0 "No"
     1 "Yes"
;
label define C330U   
     0 "No"
     1 "Yes"
;
label define C330V   
     0 "No"
     1 "Yes"
;
label define C330W   
     0 "No"
     1 "Yes"
;
label define C330XA  
     0 "No"
     1 "Yes"
;
label define C330XB  
     0 "No"
     1 "Yes"
;
label define C331    
     1 "Provided by facility"
     2 "Provided by client"
     8 "Don't know"
;
label define C340    
     1 "Current user"
     2 "Nonuser, used in past"
     3 "Nonuser, no past use"
     8 "Not determined"
;
label define C341    
     1 "Resupply/routine follow-up"
     2 "Discuss problem with method"
     3 "Desire to change or discontinue FP"
     4 "Desire to change methods - no specific problem"
     5 "Desire to discontinue - no specific problem"
     6 "Discuss other physical problem"
;
label define C342    
     0 "Decided to stop using FP"
     1 "Continued with current method"
     2 "Switched method"
     3 "Planned method switch, not received, continued with current method"
     4 "Planned method switch, not received today, discontinue current method"
;
label define C345    
     0 "Did not decide on method"
     1 "Accepted to start method"
;
label define C346    
     0 "No"
     1 "Yes"
;
label define C347    
     0 "Decided to stop/ not begin using"
     1 "Method not in stock"
     2 "Requires appointment"
     3 "Delay receiving due to health problems"
     4 "Pregnancy status uncertain"
     6 "Other"
;
label define C348    
     0 "No"
     1 "Yes"
     2 "No individual card used"
     8 "Don't know"
;
label define C351    
     0 "No"
     1 "Yes, currently"
     2 "Yes, in last 6 months"
;
label define C352A   
     0 "No"
     1 "Yes"
;
label define C352B   
     0 "No"
     1 "Yes"
;
label define C352C   
     0 "No"
     1 "Yes"
;
label define C352D   
     0 "No"
     1 "Yes"
;
label define C352E   
     0 "No"
     1 "Yes"
;
label define C352F   
     0 "No"
     1 "Yes"
;
label define C352G   
     0 "No"
     1 "Yes"
;
label define C352H   
     0 "No"
     1 "Yes"
;
label define C352I   
     0 "No"
     1 "Yes"
;
label define C352J   
     0 "No"
     1 "Yes"
;
label define C352K   
     0 "No"
     1 "Yes"
;
label define C352L   
     0 "No"
     1 "Yes"
;
label define C352O   
     0 "No"
     1 "Yes"
;
label define C352P   
     0 "No"
     1 "Yes"
;
label define C352Q   
     0 "No"
     1 "Yes"
;
label define C352R   
     0 "No"
     1 "Yes"
;
label define C352S   
     0 "No"
     1 "Yes"
;
label define C352X   
     0 "No"
     1 "Yes"
;
label define C353A   
     0 "No"
     1 "Yes, asked"
;
label define C353B   
     0 "No"
     1 "Yes, having a problem"
;
label define C353B2  
     0 "No"
     1 "Yes, having a problem"
;
label define C353C   
     0 "No"
     1 "Yes, provider suggested action"
     2 "Client didn't mention problem to provider"
     3 "Client had no problem"
     8 "Don't know"
;
label define C354    
     1 "Continue or restart same method"
     2 "Switch methods"
     3 "Stop using method due to problems"
     4 "Stop using method no problems"
;
label define C355    
     0 "No"
     1 "Yes"
;
label define C356    
     0 "No"
     1 "Yes"
;
label define C357A   
     0 "No"
     1 "Yes"
;
label define C357B   
     0 "No"
     1 "Yes"
;
label define C357C   
     0 "No"
     1 "Yes"
;
label define C357D   
     0 "No"
     1 "Yes"
;
label define C357E   
     0 "No"
     1 "Yes"
;
label define C357F   
     0 "No"
     1 "Yes"
;
label define C357G   
     0 "No"
     1 "Yes"
;
label define C357H   
     0 "No"
     1 "Yes"
;
label define C357I   
     0 "No"
     1 "Yes"
;
label define C357J   
     0 "No"
     1 "Yes"
;
label define C357K   
     0 "No"
     1 "Yes"
;
label define C357L   
     0 "No"
     1 "Yes"
;
label define C357O   
     0 "No"
     1 "Yes"
;
label define C357P   
     0 "No"
     1 "Yes"
;
label define C357Q   
     0 "No"
     1 "Yes"
;
label define C357R   
     0 "No"
     1 "Yes"
;
label define C357S   
     0 "No"
     1 "Yes"
;
label define C357X   
     0 "No"
     1 "Yes"
;
label define C358    
     0 "No"
     1 "Yes"
;
label define C359A   
     0 "No"
     1 "Yes"
;
label define C359B   
     0 "No"
     1 "Yes"
;
label define C359C   
     0 "No"
     1 "Yes"
;
label define C359D   
     0 "No"
     1 "Yes"
;
label define C359E   
     0 "No"
     1 "Yes"
;
label define C359F   
     0 "No"
     1 "Yes"
;
label define C359G   
     0 "No"
     1 "Yes"
;
label define C359H   
     0 "No"
     1 "Yes"
;
label define C359I   
     0 "No"
     1 "Yes"
;
label define C359J   
     0 "No"
     1 "Yes"
;
label define C359K   
     0 "No"
     1 "Yes"
;
label define C359L   
     0 "No"
     1 "Yes"
;
label define C359O   
     0 "No"
     1 "Yes"
;
label define C359P   
     0 "No"
     1 "Yes"
;
label define C359Q   
     0 "No"
     1 "Yes"
;
label define C359R   
     0 "No"
     1 "Yes"
;
label define C359S   
     0 "No"
     1 "Yes"
;
label define C359X   
     0 "No"
     1 "Yes"
;
label define C360A   
     0 "No"
     1 "Yes received"
     2 "Yes, received and prescribed"
     3 "Yes, prescribed only"
     4 "Continuing with method, received none"
;
label define C360B   
     0 "No"
     1 "Yes received"
     2 "Yes, received and prescribed"
     3 "Yes, prescribed only"
     4 "Continuing with method, received none"
;
label define C360C   
     0 "No"
     1 "Yes received"
     2 "Yes, received and prescribed"
     3 "Yes, prescribed only"
     4 "Continuing with method, received none"
;
label define C360D   
     0 "No"
     1 "Yes received"
     2 "Yes, received and prescribed"
     3 "Yes, prescribed only"
     4 "Continuing with method, received none"
;
label define C360E   
     0 "No"
     1 "Yes received"
     2 "Yes, received and prescribed"
     3 "Yes, prescribed only"
     4 "Continuing with method, received none"
;
label define C360F   
     0 "No"
     1 "Yes received"
     2 "Yes, received and prescribed"
     3 "Yes, prescribed only"
     4 "Continuing with method, received none"
;
label define C360G   
     0 "No"
     1 "Yes received"
     2 "Yes, received and prescribed"
     3 "Yes, prescribed only"
     4 "Continuing with method, received none"
;
label define C360H   
     0 "No"
     1 "Yes received"
     2 "Yes, received and prescribed"
     3 "Yes, prescribed only"
     4 "Continuing with method, received none"
;
label define C360I   
     0 "No"
     1 "Yes received"
     2 "Yes, received and prescribed"
     3 "Yes, prescribed only"
     4 "Continuing with method, received none"
;
label define C360J   
     0 "No"
     1 "Yes received"
     2 "Yes, received and prescribed"
     3 "Yes, prescribed only"
     4 "Continuing with method, received none"
;
label define C360K   
     0 "No"
     1 "Yes received"
     2 "Yes, received and prescribed"
     3 "Yes, prescribed only"
     4 "Continuing with method, received none"
;
label define C360L   
     0 "No"
     1 "Yes received"
     2 "Yes, received and prescribed"
     3 "Yes, prescribed only"
     4 "Continuing with method, received none"
;
label define C360O   
     0 "No"
     1 "Yes received"
     2 "Yes, received and prescribed"
     3 "Yes, prescribed only"
     4 "Continuing with method, received none"
;
label define C360P   
     0 "No"
     1 "Yes received"
     2 "Yes, received and prescribed"
     3 "Yes, prescribed only"
     4 "Continuing with method, received none"
;
label define C360Q   
     0 "No"
     1 "Yes received"
     2 "Yes, received and prescribed"
     3 "Yes, prescribed only"
     4 "Continuing with method, received none"
;
label define C360R   
     0 "No"
     1 "Yes received"
     2 "Yes, received and prescribed"
     3 "Yes, prescribed only"
     4 "Continuing with method, received none"
;
label define C360S   
     0 "No"
     1 "Yes received"
     2 "Yes, received and prescribed"
     3 "Yes, prescribed only"
     4 "Continuing with method, received none"
;
label define C360X   
     0 "No"
     1 "Yes received"
     2 "Yes, received and prescribed"
     3 "Yes, prescribed only"
     4 "Continuing with method, received none"
;
label define C360Y   
     0 "No some method received or prescribed or continuing with current method"
     1 "Yes none"
;
label define C361    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define C362A   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define C362B   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define C362C   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define C362D   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define C363A   
     1 "Once a day"
     2 "Other response"
     8 "Don't know"
;
label define C363D   
     1 "1 month"
     2 "Other response"
     8 "Don't know"
;
label define C363E   
     1 "2-3 months"
     2 "Other response"
     8 "Don't know"
;
label define C363G   
     1 "3-5 years"
     2 "Other response"
     8 "Don't know"
;
label define C363I   
     1 "Once"
     2 "Other response"
     8 "Don't know"
;
label define C363J   
     1 "Any oil or lubricant"
     2 "Other response"
     8 "Don't know"
;
label define C363J2  
     1 "Only once"
     2 "Other response"
     8 "Don't know"
;
label define C363K   
     1 "Check string"
     2 "Other response"
     8 "Don't know"
;
label define C363O1  
     0 "No, not mentioned"
     1 "Yes, body temperature rises"
;
label define C363O2  
     0 "No, not mentioned"
     1 "Yes, mucus in vagina"
;
label define C363O3  
     0 "No, not mentioned"
     1 "Yes, days 12-16 of cycle"
;
label define C363O3A 
     0 "No, not mentioned"
     1 "Yes, white bead days"
;
label define C363O4  
     0 "No, not mentioned"
     1 "Yes, other way"
;
label define C363O5  
     0 "No, mentioned some way"
     1 "Yes, doesn't know way to identify fertile days"
;
label define C363P   
     0 "No, cannot use"
     1 "Yes, can use"
     8 "Don't know"
;
label define C363Q1  
     1 "Immediate protection"
     2 "Wait 1-3 months"
     3 "Only after 3 months or 30 ejaculations"
     8 "Don't know"
;
label define C363Q2  
     0 "Cannot impregnate"
     1 "Yes, definitely can impregnate"
     2 "Slight risk of impregnating"
     8 "Don't know"
;
label define C363R1  
     1 "Immediate protection"
     2 "Wait 1-3 months"
     3 "Only after 3 months"
     8 "Don't know"
;
label define C363R2  
     0 "Cannot become pregnant"
     1 "Yes, definitely can become pregnant"
     2 "Slight risk of becoming pregnant"
     8 "Don't know"
;
label define SXF107A 
     0 "No"
     1 "Yes"
;
label define SXF107B 
     0 "No"
     1 "Yes"
;
label define SXF107C 
     0 "No"
     1 "Yes"
;
label define SXF107D 
     0 "No"
     1 "Yes"
;
label define SXF107E 
     0 "No"
     1 "Yes"
;
label define SXF107F 
     0 "No"
     1 "Yes"
;
label define SXF107G 
     0 "No"
     1 "Yes"
;
label define SXF107H 
     0 "No"
     1 "Yes"
;
label define SXF107I 
     0 "No"
     1 "Yes"
;
label define SXF107J 
     0 "No"
     1 "Yes"
;
label define SXF107X 
     0 "No"
     1 "Yes"
;

#delimit cr
label values c001     C001    
label values c003     C003    
label values c007     C007    
label values c008     C008    
label values c020a    C020A   
label values c020b    C020B   
label values c021     C021    
label values c022     C022    
label values c023     C023    
label values c024     C024    
label values c501     C501    
label values c502a    C502A   
label values c502b    C502B   
label values c502c    C502C   
label values c502e    C502E   
label values c502f    C502F   
label values c502g    C502G   
label values c502h    C502H   
label values c502i    C502I   
label values c502j    C502J   
label values c502k    C502K   
label values c502l    C502L   
label values c503     C503    
label values c504     C504    
label values c505     C505    
label values c507     C507    
label values c508     C508    
label values c510     C510    
label values c511     C511    
label values c512     C512    
label values c514     C514    
label values c515     C515    
label values c517a    C517A   
label values c517b    C517B   
label values c518a    C518A   
label values c518b    C518B   
label values c520     C520    
label values c521     C521    
label values c522     C522    
label values scdepart SCDEPART
label values sclocal  SCLOCAL 
label values c301a    C301A   
label values c301b    C301B   
label values c302a    C302A   
label values c302b    C302B   
label values c302c    C302C   
label values c302e    C302E   
label values c302f    C302F   
label values c302g    C302G   
label values c302h    C302H   
label values c302i    C302I   
label values c302y1   C302Y1  
label values c302y2   C302Y2  
label values c303a    C303A   
label values c303b    C303B   
label values c303c    C303C   
label values c303d    C303D   
label values c303e    C303E   
label values c303f    C303F   
label values c303g    C303G   
label values c303y    C303Y   
label values cf303a   CF303A  
label values cf303b   CF303B  
label values cf303xa  CF303XA 
label values c304a    C304A   
label values c304b    C304B   
label values c304c    C304C   
label values c304y    C304Y   
label values c305a    C305A   
label values c305b    C305B   
label values c305c    C305C   
label values c305d    C305D   
label values c305e    C305E   
label values c305f    C305F   
label values c305g    C305G   
label values c305y    C305Y   
label values c306a    C306A   
label values c306b    C306B   
label values c306c    C306C   
label values c306d    C306D   
label values c306e    C306E   
label values c306f    C306F   
label values c306g    C306G   
label values c306h    C306H   
label values c306i    C306I   
label values c306j    C306J   
label values c306k    C306K   
label values c306l    C306L   
label values c306o    C306O   
label values c306p    C306P   
label values c306q    C306Q   
label values c306r    C306R   
label values c306s    C306S   
label values c306x    C306X   
label values c306y    C306Y   
label values c307a    C307A   
label values c307b    C307B   
label values c307c    C307C   
label values c307d    C307D   
label values c307e    C307E   
label values c307f    C307F   
label values c307y    C307Y   
label values c308a    C308A   
label values c308b    C308B   
label values c308c    C308C   
label values c308d    C308D   
label values c308e    C308E   
label values c308y    C308Y   
label values c309a    C309A   
label values c309b    C309B   
label values c309c    C309C   
label values c309d    C309D   
label values c309e    C309E   
label values c309y    C309Y   
label values c310a    C310A   
label values c310b    C310B   
label values c310c    C310C   
label values c310d    C310D   
label values c310e    C310E   
label values c310f    C310F   
label values c310y    C310Y   
label values c311a    C311A   
label values c311b    C311B   
label values c311c    C311C   
label values c311d    C311D   
label values c311e    C311E   
label values c311f    C311F   
label values c311y    C311Y   
label values c313a    C313A   
label values c313b    C313B   
label values c313c    C313C   
label values c313y    C313Y   
label values c314a    C314A   
label values c314b    C314B   
label values c314c    C314C   
label values c314d    C314D   
label values c314e    C314E   
label values c314y    C314Y   
label values c315a    C315A   
label values c315c    C315C   
label values c315d    C315D   
label values c315e    C315E   
label values c315f    C315F   
label values c315g    C315G   
label values c315h    C315H   
label values c315y    C315Y   
label values c316     C316    
label values c317     C317    
label values c318     C318    
label values c319     C319    
label values c320     C320    
label values c321     C321    
label values c322     C322    
label values c323a    C323A   
label values c323b    C323B   
label values c323c    C323C   
label values c323d    C323D   
label values c323e    C323E   
label values c323f    C323F   
label values c323g    C323G   
label values c323h    C323H   
label values c323i    C323I   
label values c323j    C323J   
label values c323k    C323K   
label values c323l    C323L   
label values c323m1   C323M1  
label values c323m    C323M   
label values c323n    C323N   
label values c323o    C323O   
label values c324     C324    
label values c325a    C325A   
label values c325b    C325B   
label values c325c    C325C   
label values c325d    C325D   
label values c325e    C325E   
label values c325f    C325F   
label values c325g    C325G   
label values c325h    C325H   
label values c325i    C325I   
label values c325i2   C325I2  
label values c325j    C325J   
label values c325k    C325K   
label values c325l    C325L   
label values c325m    C325M   
label values c325n    C325N   
label values c325n2   C325N2  
label values c325o    C325O   
label values c325o2   C325O2  
label values c325p    C325P   
label values c325q    C325Q   
label values c325r    C325R   
label values c325s    C325S   
label values c325t    C325T   
label values c325u    C325U   
label values c325v    C325V   
label values c325w    C325W   
label values c325xa   C325XA  
label values c325xb   C325XB  
label values c325xc   C325XC  
label values c325y    C325Y   
label values c326     C326    
label values c327a    C327A   
label values c327b    C327B   
label values c327c    C327C   
label values c327c2   C327C2  
label values c327c3   C327C3  
label values c327d    C327D   
label values c327d2   C327D2  
label values c327e    C327E   
label values c327e2   C327E2  
label values c327f    C327F   
label values c327g    C327G   
label values c327h    C327H   
label values c327i    C327I   
label values c327j    C327J   
label values c327k    C327K   
label values c327l    C327L   
label values c327m    C327M   
label values c328     C328    
label values c329     C329    
label values c330a    C330A   
label values c330b    C330B   
label values c330c    C330C   
label values c330d    C330D   
label values c330e    C330E   
label values c330f    C330F   
label values c330g    C330G   
label values c330h    C330H   
label values c330i    C330I   
label values c330j    C330J   
label values c330k    C330K   
label values c330l    C330L   
label values c330m    C330M   
label values c330n    C330N   
label values c330o    C330O   
label values c330p    C330P   
label values c330p2   C330P2  
label values c330q    C330Q   
label values c330r    C330R   
label values c330s    C330S   
label values c330t    C330T   
label values c330u    C330U   
label values c330v    C330V   
label values c330w    C330W   
label values c330xa   C330XA  
label values c330xb   C330XB  
label values c331     C331    
label values c340     C340    
label values c341     C341    
label values c342     C342    
label values c345     C345    
label values c346     C346    
label values c347     C347    
label values c348     C348    
label values c351     C351    
label values c352a    C352A   
label values c352b    C352B   
label values c352c    C352C   
label values c352d    C352D   
label values c352e    C352E   
label values c352f    C352F   
label values c352g    C352G   
label values c352h    C352H   
label values c352i    C352I   
label values c352j    C352J   
label values c352k    C352K   
label values c352l    C352L   
label values c352o    C352O   
label values c352p    C352P   
label values c352q    C352Q   
label values c352r    C352R   
label values c352s    C352S   
label values c352x    C352X   
label values c353a    C353A   
label values c353b    C353B   
label values c353b2   C353B2  
label values c353c    C353C   
label values c354     C354    
label values c355     C355    
label values c356     C356    
label values c357a    C357A   
label values c357b    C357B   
label values c357c    C357C   
label values c357d    C357D   
label values c357e    C357E   
label values c357f    C357F   
label values c357g    C357G   
label values c357h    C357H   
label values c357i    C357I   
label values c357j    C357J   
label values c357k    C357K   
label values c357l    C357L   
label values c357o    C357O   
label values c357p    C357P   
label values c357q    C357Q   
label values c357r    C357R   
label values c357s    C357S   
label values c357x    C357X   
label values c358     C358    
label values c359a    C359A   
label values c359b    C359B   
label values c359c    C359C   
label values c359d    C359D   
label values c359e    C359E   
label values c359f    C359F   
label values c359g    C359G   
label values c359h    C359H   
label values c359i    C359I   
label values c359j    C359J   
label values c359k    C359K   
label values c359l    C359L   
label values c359o    C359O   
label values c359p    C359P   
label values c359q    C359Q   
label values c359r    C359R   
label values c359s    C359S   
label values c359x    C359X   
label values c360a    C360A   
label values c360b    C360B   
label values c360c    C360C   
label values c360d    C360D   
label values c360e    C360E   
label values c360f    C360F   
label values c360g    C360G   
label values c360h    C360H   
label values c360i    C360I   
label values c360j    C360J   
label values c360k    C360K   
label values c360l    C360L   
label values c360o    C360O   
label values c360p    C360P   
label values c360q    C360Q   
label values c360r    C360R   
label values c360s    C360S   
label values c360x    C360X   
label values c360y    C360Y   
label values c361     C361    
label values c362a    C362A   
label values c362b    C362B   
label values c362c    C362C   
label values c362d    C362D   
label values c363a    C363A   
label values c363d    C363D   
label values c363e    C363E   
label values c363g    C363G   
label values c363i    C363I   
label values c363j    C363J   
label values c363j2   C363J2  
label values c363k    C363K   
label values c363o1   C363O1  
label values c363o2   C363O2  
label values c363o3   C363O3  
label values c363o3a  C363O3A 
label values c363o4   C363O4  
label values c363o5   C363O5  
label values c363p    C363P   
label values c363q1   C363Q1  
label values c363q2   C363Q2  
label values c363r1   C363R1  
label values c363r2   C363R2  
label values sxf107a  SXF107A 
label values sxf107b  SXF107B 
label values sxf107c  SXF107C 
label values sxf107d  SXF107D 
label values sxf107e  SXF107E 
label values sxf107f  SXF107F 
label values sxf107g  SXF107G 
label values sxf107h  SXF107H 
label values sxf107i  SXF107I 
label values sxf107j  SXF107J 
label values sxf107x  SXF107X 
